### ISSUE TITLE
what is the dataroot_HR_bg in train_sftgan.json?

### ISSUE THREAD

**Issue by guyuexiwen** [xinntao/BasicSR#10]
what is the dataroot_HR_bg in train_sftgan.json?

**Comment by xinntao** [comment]
@guyuexiwen 
**dataroot_HR_bg**  is the path of HR images for background (bg), here, SFTGAN uses DIV2K images as the training images for the background category.
A simple description of the json files is updated [here](https://github.com/xinntao/BasicSR/blob/master/codes/options/README.md).
