### ISSUE TITLE
Change HR_size to 192 but got error

### ISSUE THREAD

**Issue by TeeboneTing** [xinntao/BasicSR#100]
Hi,
  When I start training my ESRGAN with HR_size = 192 but got errors shown below, any ideas?

> Traceback (most recent call last):
>   File "train.py", line 232, in <module>
>     main()
>   File "train.py", line 165, in main
>     model.optimize_parameters(current_step)
>   File "/opt/src/codes/models/SRRaGAN_model.py", line 133, in optimize_parameters
>     pred_g_fake = self.netD(self.fake_H)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
>     outputs = self.parallel_apply(replicas, inputs, kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
>     return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
>     raise output
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
>     output = module(*input, **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/opt/src/codes/models/modules/architecture.py", line 128, in forward
>     x = self.classifier(x)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
>     input = module(input)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 67, in forward
>     return F.linear(input, self.weight, self.bias)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1352, in linear
>     ret = torch.addmm(torch.jit._unwrap_optional(bias), input, weight.t())
> RuntimeError: size mismatch, m1: [6 x 18432], m2: [8192 x 100] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:266
> 
> 

Here is my json config file:
```

{
  "name": "RRDB_ESRGAN_x4_ANIME" //  please remove "debug_" during training
  , "use_tb_logger": true
  , "model":"srragan"
  , "scale": 4
  , "gpu_ids": [0,1,2,3,4,5]

  , "datasets": {
    "train": {
      "name": "ANIME"
      , "mode": "LRHR"
      , "dataroot_HR": "/dataset/ANIME"
      , "subset_file": null
      , "use_shuffle": true
      , "n_workers": 8
      , "batch_size": 32
      , "HR_size": 192
      , "use_flip": true
      , "use_rot": true
    }
    , "val": {
      "name": "ANIME_val"
      , "mode": "LRHR"
      , "dataroot_HR": "/dataset/ANIME_val/test_clear_HR"
    }
  }

  , "path": {
    "root": "/models"
    // , "resume_state": "../experiments/debug_002_RRDB_ESRGAN_x4_DIV2K/training_state/16.state"
    //, "pretrain_model_G": "/models/pretrained_models/RRDB_PSNR_x4.pth"
    // , "pretrain_model_D": ""
  }

  , "network_G": {
    "which_model_G": "RRDB_net" // RRDB_net | sr_resnet
    , "norm_type": null
    , "mode": "CNA"
    , "nf": 64
    , "nb": 23
    , "in_nc": 3
    , "out_nc": 3
    , "gc": 32
    , "group": 1
  }
  , "network_D": {
    "which_model_D": "discriminator_vgg_128"
    , "norm_type": "batch"
    , "act_type": "leakyrelu"
    , "mode": "CNA"
    , "nf": 64
    , "in_nc": 3
  }

  , "train": {
    "lr_G": 1e-4
    , "weight_decay_G": 0
    , "beta1_G": 0.9
    , "lr_D": 1e-4
    , "weight_decay_D": 0
    , "beta1_D": 0.9
    , "lr_scheme": "MultiStepLR"
    , "lr_steps": [50000, 100000, 200000, 300000]
    , "lr_gamma": 0.5

    , "pixel_criterion": "l1"
    , "pixel_weight": 1e-2
    , "feature_criterion": "l1"
    , "feature_weight": 1
    , "gan_type": "vanilla"
    , "gan_weight": 5e-3

    //for wgan-gp
    // , "D_update_ratio": 1
    // , "D_init_iters": 0
    // , "gp_weigth": 10

    , "manual_seed": 0
    , "niter": 1e5
    , "val_freq": 5e3
  }

  , "logger": {
    "print_freq": 200
    , "save_checkpoint_freq": 1e4
  }
}
```

**Comment by xinntao** [comment]
When training with SRRaGAN model, the current Discriminator takes 128*128 patches as inputs. If you want to train with 192*192 patches, you need to modify the architecture of the discriminator.

**Comment by TeeboneTing** [comment]
Answered by myself: Not only change "HR_size": 192 but also change "which_model_D": "discriminator_vgg_128" to "which_model_D": "discriminator_vgg_192" and everything works.
