### ISSUE TITLE
without RaGAN loss in your train code 

### ISSUE THREAD

**Issue by Johnson-yue** [xinntao/BasicSR#103]
In your **train_ESRGAN.json**  file  the [gan_type] is vanilla,  and In loss.py for function of GANLoss
you only implement ['vanilla', 'lsgan', 'wgan-gp''] , is also not including "RaGAN loss" as your paper said.

And question2： you update G before update D ???

**Comment by xinntao** [comment]
RaGAN loss is in this file https://github.com/xinntao/BasicSR/blob/master/codes/models/SRRaGAN_model.py

It is not so important to update G or D first.

**Comment by ira7bar** [comment]
@Johnson-yue, the ESRGANModel class has the RaGAN loss already built in the code (https://github.com/xinntao/BasicSR/blob/master/basicsr/models/esrgan_model.py#L40), so you can simply set the "model_type" config parameter to "ESRGANModel" to use it.

**Comment by Johnson-yue** [comment]
thank you
