### ISSUE TITLE
Change input/output channel

### ISSUE THREAD

**Issue by BeepBump** [xinntao/BasicSR#104]
Hi Xintao,

I currently study GAN to help super-resolution task.

I do some transform of LR and HR image before feeding in the network. (modify LRHR_dataset.py)
However, I need to do the inverse transform to the SR image, so where can I modify the code to do the inverse transform to the network output?

More specifically, my input channel is now 12 not 3.

**Comment by xinntao** [comment]
So you want the network output has 12 channels?
If so, you can modify the corresponding network strucutre, https://github.com/xinntao/BasicSR/blob/master/codes/models/modules/architecture.py

**Comment by BeepBump** [comment]
Thanks for answer, I have already modified the network structure.
However, in validation, I don't know where to conduct the transform so it is still 3-channel input.(Or if I modify LRHR_dataset.py, it will also do the transform on the validation dataset?)
And where can I modify the code to do the inverse transform to the network output? (Now the output is 12 channel and I need to do inverse transform to change the number of channel back to 3)

**Comment by xinntao** [comment]
@BeepBump 
1. the validation transformation can also be done in ` LRHR_dataset.py`. Maybe you only perform the transformation in the training phase. May need to check it. 
2. After obtaining the 12-channel outputs, you can do the inverse transform in the `xxx_model.py` file, 
for example, you can change it in the train and test phase by modifying the following functions.
https://github.com/xinntao/BasicSR/blob/36984e8bb1cd4269397bb15361a4221d26d4235a/codes/models/SR_model.py#L66-L80

**Comment by BeepBump** [comment]
Really appreciate about ur reply. Now, I can train SRResNet.
However, for SRGAN, it need the pretrain model for VGG net.
Does it no matter for changing the number of channel in reading pretrain SRResNet?
