### ISSUE TITLE
Q: Real-time higher-res images (like a movie?)

### ISSUE THREAD

**Issue by danger89** [xinntao/BasicSR#11]
Hi,

I was wondering is it possible with BasicSR/ESRGAN to create real-time 2x or 4x higher resolution from a video stream of 512x448 pixels with let's say 20 or 30 FPS?

Real-time, I mean a stream of input data, which creates a stream of output data (eg. like a movie as input).

Kind regards,
Melroy

**Comment by xinntao** [comment]
@danger89 
Unfortunately, the ESRGAN model is too large for real-time application. 
Real-time SR algorithm is also another hot research topic. For example, [FSRCNN](http://mmlab.ie.cuhk.edu.hk/projects/FSRCNN.html) and many other works, and a recent ECCV [workshop competition](http://ai-benchmark.com/challenge.html) about SR in the mobile application. 

For real-time SR, you should carefully design the network structure and deal with other things. And **BasicSR** is just a training framework. You can still use it to train your SR-algorithms with fast speed. 

BTW, 
1. For video, there is another research topic, Video SR, which is more suitable for videos (Like maintaining time consistence in videos and using more information among frames).
2. Videos in real-world, like movies, are also with noise and unknown downsampling kernels. It is not so easy to cope with these real-world problems.
