### ISSUE TITLE
File structure of data sets. Tiling of pictures

### ISSUE THREAD

**Issue by surfingnirvana** [xinntao/BasicSR#110]
How do i have to tile my png/jpg files to work with ESRGAN. If i apply the tiling script (extract_subimgs_single.py) to my 1920x1080 pictures there will be only a single tile out of one picture. What is the meaning of these variables (crop_sz  step  thres_sz). What is the recommended folder structure for the training and validation tiles/pictures? Thank you very much.

**Comment by xinntao** [comment]
1. After running the `extract_subimgs_single.py` script, there should be several sub-images (with the suffix '_s000, _s001, ...') in the folder.
2. `crop_sz` is the size of the cropped sub-image;
`step`: when cropping, we use a sliding window on the large original image. The step is the distance between the two adjacent windows
`thres_sz`: when the number of remainning pixels (of each row and each column) is smaller than the threshold size, it will drop them. 
3. It is flexible and you can specify these paths in the config files - `dataroot_HR` and `dataroot_LR`.
