### ISSUE TITLE
Why do you choose the gan weight to be 5e-3?

### ISSUE THREAD

**Issue by Litou1** [xinntao/BasicSR#118]
Can you clarify why do you choose 0.005 as gan weight and 1 as feature weight?  I feel that 0.005 is too small to utilize the power of GAN? Maybe I am wrong here. Could you help me understand?
Thank you!

**Comment by xinntao** [comment]
The weights are empirically selected by experiments. 
Too larger GAN weights will introduce much noise and even distort the textures.

**Comment by Litou1** [comment]
Thanks! Do you also weight perceptual loss as srgan paper suggested? https://arxiv.org/pdf/1609.04802.pdf
In section 3.2, they seem to rescale vgg loss by 12.75 to be comparable to pixel loss, I was wondering if you would have done the same?

**Comment by xinntao** [comment]
No, we do not rescale vgg loss to be comparable to pixel loss.

**Comment by Litou1** [comment]
Thank you!
