### ISSUE TITLE
extract_subimgs_single

### ISSUE THREAD

**Issue by Feiyu-Zhang** [xinntao/BasicSR#120]
I run scripts/extract_subimgs_single.py , but I only get 12 sub_img from 12 different images. Are there some bugs in scripts/extract_subimgs_single.py?

**Comment by xinntao** [comment]
It works at my end. 
You may want to check your image size or others.

**Comment by Feiyu-Zhang** [comment]
> It works at my end.
> You may want to check your image size or others.

Thanks.
I shouldn't extract sub-images of LR images. HAHA, I'm silly.

**Comment by Cugtyt** [comment]
@Feiyu-Zhang May I ask why shouldn't extract sub-images of LR images? if there are equal numbers of LR and HR images, and HR is extracted while LR not, then the number of images are not equal, right?

I got this error:

```
AssertionError: HR and LR datasets have different number of images - 5000, 140400.
``` 

My LR and HR images are 5000, but after extract HR is 140400, but I saw that extract_subimgs_single.py that crop 480 size that may not suitable for LR, so can you give specific information about how you solve it?

**Comment by Feiyu-Zhang** [comment]
> @Feiyu-Zhang May I ask why shouldn't extract sub-images of LR images? if there are equal numbers of LR and HR images, and HR is extracted while LR not, then the number of images are not equal, right?
> 
> I got this error:
> 
> ```
> AssertionError: HR and LR datasets have different number of images - 5000, 140400.
> ```
> 
> My LR and HR images are 5000, but after extract HR is 140400, but I saw that extract_subimgs_single.py that crop 480 size that may not suitable for LR, so can you give specific information about how you solve it?

At last, I didn't extract the sub-images of HR and LR.
