### ISSUE TITLE
meaning of "use_flip": true and "use_rot": true

### ISSUE THREAD

**Issue by surfingnirvana** [xinntao/BasicSR#124]
Hi xinntao, could you provide information about the two variables "use_flip": true and "use_rot": true in the train_ESRGAN.json? Assuming i would set them to false. What would be the difference when training? Thank you.

**Comment by xinntao** [comment]
They are used for data augmentation. 
If you set  `use_flip` to true, it will randomly flip the patches horizontally during training. If you set `use_rot` to true, it will randomly rotate and do vertical flips.
More details in https://github.com/xinntao/BasicSR/blob/36984e8bb1cd4269397bb15361a4221d26d4235a/codes/data/util.py#L94-L106

If you set them to false, the dataloader will not do data augmentation.
