### ISSUE TITLE
create lmdb when data is large

### ISSUE THREAD

**Issue by Cugtyt** [xinntao/BasicSR#125]
I noted that in create_lmdb.py, all images will be loaded into a list, but my dataset is large and memory is limited, so how can I solve it?

**Comment by xinntao** [comment]
You can modify the creating lmdb codes to use less memory. Actually, you can read part of the data and then write it to lmdb. 

Ref: https://github.com/xinntao/BasicSR/issues/57

**Comment by Cugtyt** [comment]
Is it right to read each image and then put it?

``` python
with env.begin(write=True) as txn:  # txn is a Transaction object
    for i, v in enumerate(img_list):
        pbar.update('Write {}'.format(v))
        base_name = os.path.splitext(os.path.basename(v))[0]
        key = base_name.encode('ascii')
        data = cv2.imread(v, cv2.IMREAD_UNCHANGED) #dataset[i] <------- this is the change
        if data.ndim == 2:
            H, W = data.shape
            C = 1
        else:
            H, W, C = data.shape
        meta_key = (base_name + '.meta').encode('ascii')
        meta = '{:d}, {:d}, {:d}'.format(H, W, C)
        # The encode is only essential in Python 3
        txn.put(key, data)
        txn.put(meta_key, meta.encode('ascii'))
```

But still out of my memory.

**Comment by xinntao** [comment]
I have not tried to write images to lmdb one by one. 

May try to exchange the `with env.begin(write=True) as txn` and `for i, v in enumerate(img_list)`. 

If it still does not work. You may try to close the lmdb after writing and then open it in the for loop.
