### ISSUE TITLE
Error in training wgan-gp

### ISSUE THREAD

**Issue by BK1024** [xinntao/BasicSR#126]
Hi xinntao, in `optimize_parameters(self, step)`from /BasicSR/codes/models/SRGAN_model.py, , I found python complaining about the following line from your implementation of wgan-gp:
`interp_crit, _ = self.netD(interp)`. `self.netD(interp)` will only return one value for the randomly interpolated image. Is it just a typo or the wgan-gp part is yet to be completed? 

Also, I found this line below the above line: `l_d_gp = self.l_gp_w * self.cri_gp(interp, interp_crit)  # maybe wrong in cls?`. This concerns me...would you mind explaining what might be wrong? Thank you!

**Comment by xinntao** [comment]
In the file https://github.com/xinntao/BasicSR/blob/master/codes/models/SRGAN_model.py (SRGAN model), the wgan-gp could work. 
The `interp_crit, _ = self.netD(interp)` you mentioned is in the SFTGAN_ACD_model.
And SFTGAN does not support WAGN-GP.

**Comment by BK1024** [comment]
The following lines are the code snippet I am referring to:

[https://github.com/xinntao/BasicSR/blob/36984e8bb1cd4269397bb15361a4221d26d4235a/codes/models/SRGAN_model.py#L148-L157](url)

**Comment by xinntao** [comment]
Emmm, I made a mistake....+_+

It should be `interp_crit = self.netD(interp) ` in SRGAN model. 
 `# maybe wrong in cls?  ` I mean that it may be wrong in SFTGAN model. 

A long time ago, I use this code to run SRGAN with WGAN-GP and it could run. But I did not observe improvements compared to vanilla GAN.

I will correct these codes. Thanks~

**Comment by BK1024** [comment]
Got it! Hope this helps.
