### ISSUE TITLE
Should LR imgs also extract_subimgs_single.py ?

### ISSUE THREAD

**Issue by Cugtyt** [xinntao/BasicSR#132]
If should, the problem is the crop_sz is not suitable for LR imgs, 480 may bigger than LR.
if shouldn't, the problem is the numbers of LR and HR are different, error of  `HR and LR datasets have different number of images...`
Can you give more information about that?

**Comment by xinntao** [comment]
You need different configs for HR and LR: 
for example X2 

HR:
```
crop_sz = 480
step = 240
thres_sz = 48
```

LR:
```
crop_sz = 240
step = 120
thres_sz = 24
```
