### ISSUE TITLE
MINC Pretrained Model

### ISSUE THREAD

**Issue by Queuecumber** [xinntao/BasicSR#134]
I'm looking for the pretrained MINC model, your code references `../experiments/pretrained_models/VGG16minc_53.pth` and according to docs, anything in the `pretrained_models` folder would be on google drive, but I didnt see that file there. Do you have the MINC model or is there another way I can obtain it?

**Comment by xinntao** [comment]
You can download it from https://drive.google.com/open?id=1MoWRt05VBzvKFMrAJrASnjvOFi3MUCcE
This model is from the original Caffe model and modifications have been done to meet the requirements (1. BGR-> RGB; 2, the input should be in the range [0,1])

**Comment by Queuecumber** [comment]
Great, thanks a lot

**Comment by JoshuaEbenezer** [comment]
Hi this link has expired. Can you please share it again? I'm unable to convert the caffe model to pytorch
