### ISSUE TITLE
Hello,what's the difference between debug mode and not when training,just parameter difference???

### ISSUE THREAD

**Issue by SeriouslyHAO** [xinntao/BasicSR#148]

**Comment by SlimRG** [comment]
debugmode ignore errors
so if pytorch is broken, you will see training proccess (but there was no training process)
P.S. Sowwy for my english, я русский

**Comment by SeriouslyHAO** [comment]
thx for repely

**Comment by xinntao** [comment]
debug mode will print information more frequently. It will let you know errors more quickly without waiting for longer training time. 
After making sure the codes can run without errors, you can remove the `debug`  and start a normal training.

**Comment by SeriouslyHAO** [comment]
ok,thx.
