### ISSUE TITLE
About the Bicubic Interpolation

### ISSUE THREAD

**Issue by FlyingCarrot** [xinntao/BasicSR#15]
Thanks for your excellent repository! But I wonder if there is any difference between the OpenCV build-in Bicubic interpolation and the Bicubic algorithm you implemented in codes/data/util.py.

**Comment by xinntao** [comment]
Hi, @FlyingCarrot 
There is a difference.

The **MATLAB Bicubic** interpolation uses **anti-aliasing** when downsizing an image.  And **OpenCV Bicubic interpolation** does not have anti-aliasing. 
See more info [imresize-trying-to-understand-the-bicubic-interpolation](https://stackoverflow.com/questions/26823140/imresize-trying-to-understand-the-bicubic-interpolation) 

and [matlab-vs-c-vs-opencv-imresize](https://stackoverflow.com/questions/26812289/matlab-vs-c-vs-opencv-imresize/26812346#26812346) 

and [what-is-the-difference-between-opencvs-and-matlabs-bicubic-algorithm](https://stackoverflow.com/questions/22092744/what-is-the-difference-between-opencvs-and-matlabs-bicubic-algorithm).

The implementation in codes/data/util.py micmics what have done in MATLAB. It has almost the same  results, but a bit slower than MATLAB's.
