### ISSUE TITLE
Real-time video upscaling

### ISSUE THREAD

**Issue by kenrubiooo** [xinntao/BasicSR#154]
Hi @xinntao,

I was wondering if this can be used for real-time video super resolution. Moreover, what do the variables in_nc, out_nc, nf, nb, gc mean? Thank you!

**Comment by xinntao** [comment]
I am afraid that it is too slow for real-time video SR. 
I think you can know the meanings from the [network definition file](https://github.com/xinntao/BasicSR/blob/master/codes/models/modules/RRDBNet_arch.py)

**Comment by kenrubiooo** [comment]
Hi @xinntao,

I tried using the ESRGAN for video upscaling. The quality is reduced when upscaled due to movements. The speed is acceptable but not that fast. Thank you for replying!
