### ISSUE TITLE
The create_lmdb.py doesn't work with the same filenames

### ISSUE THREAD

**Issue by huuquan1994** [xinntao/BasicSR#16]
Tried to create my own lmdb file using the `create_lmdb.py` file.
I found that the script only works with different filename cause it uses that filename (basename) as key.

My path is somewhat like this:
```
/home/Dataset/SISR/Class_A/XXXX.png
/home/Dataset/SISR/Class_B/XXXX.png
/home/Dataset/SISR/Class_C/XXXX.png
```
Filenames are the same but the content is different. The `create_lmdb.py` will create only 1 key (it means the size of dataset will be 1 instead of 3 files)

The only solution I have right now is to rename all image filenames so that they do not duplicate. Then run the code to generate the lmdb file. But it seems to be not the convenient way.
Do you have any better ideas? Thanks

____________________________________________________________________________________________
[UPDATED] My solution is to add the iterator `i` with basename so that they will have a unique name.
I changed the line #33 in the [create_lmdb.py](https://github.com/xinntao/BasicSR/blob/master/codes/scripts/create_lmdb.py) to:
`base_name = str(i) + "_" + os.path.splitext(os.path.basename(v))[0]`

**Comment by xinntao** [comment]
@huuquan1994 

Your solution is a good way to create unique keys.
