### ISSUE TITLE
maybe  mistype:logger.info('Loading model for D [{:s}] ...'.format(load_path_G))

### ISSUE THREAD

**Issue by davincibj** [xinntao/BasicSR#164]
BasicSR/codes/models/SRGAN_model.py

def load(self):
        load_path_G = self.opt['path']['pretrain_model_G']
        if load_path_G is not None:
            logger.info('Loading model for G [{:s}] ...'.format(load_path_G))
            self.load_network(load_path_G, self.netG, self.opt['path']['strict_load'])
        load_path_D = self.opt['path']['pretrain_model_D']
        if self.opt['is_train'] and load_path_D is not None:
            logger.info('Loading model for D [{:s}] ...'.format(load_path_G)) #<---------should be load_path_D?
            self.load_network(load_path_D, self.netD, self.opt['path']['strict_load'])

**Comment by xinntao** [comment]
Thanks. It should be load_path_D.
