### ISSUE TITLE
Training Dataset Error

### ISSUE THREAD

**Issue by pjh1023** [xinntao/BasicSR#167]
Hi, I am trying to train the SR model with my own dataset.
Currently, I am able to successfully run the extract_subimgs_single.py code with the setting of
n_thread = 20
crop_sz = 480
step = 240
thres_sz = 40

However, by cropping both the LR and HR images, it gave the following error when trying to run the train.py

-----------------------------------------------------------------------------------
export CUDA_VISIBLE_DEVICES=2
Disabled distributed training.
Path already exists. Rename it to [/home/pjh2/ESRGAN/BasicSR/experiments/001_MSRResNetx4_scratch_Grid_archived_190703-212811]
19-07-03 21:28:11.445 - INFO:   name: 001_MSRResNetx4_scratch_Grid
  use_tb_logger: True
  model: sr
  distortion: sr
  scale: 4
  gpu_ids: [2]
  datasets:[
    train:[
      name: DIV2K
      mode: LQGT
      dataroot_GT: /home/pjh2/ESRGAN/BasicSR/dataset2.0/train_x-rayOnly_verticalOnly/Sup_crop
      dataroot_LQ: /home/pjh2/ESRGAN/BasicSR/dataset2.0/train_x-rayOnly_verticalOnly/Grid_crop
      use_shuffle: True
      n_workers: 6
      batch_size: 16
      GT_size: 128
      use_flip: True
      use_rot: True
      color: RGB
      phase: train
      scale: 4
      data_type: img
    ]
    val:[
      name: val_set5
      mode: LQGT
      dataroot_GT: /home/pjh2/ESRGAN/BasicSR/dataset2.0/val/Sup_crop
      dataroot_LQ: /home/pjh2/ESRGAN/BasicSR/dataset2.0/val/Grid_crop
      phase: val
      scale: 4
      data_type: img
    ]
  ]
  network_G:[
    which_model_G: MSRResNet
    in_nc: 3
    out_nc: 3
    nf: 64
    nb: 16
    upscale: 4
    scale: 4
  ]
  path:[
    pretrain_model_G: None
    strict_load: True
    resume_state: None
    root: /home/pjh2/ESRGAN/BasicSR
    experiments_root: /home/pjh2/ESRGAN/BasicSR/experiments/001_MSRResNetx4_scratch_Grid
    models: /home/pjh2/ESRGAN/BasicSR/experiments/001_MSRResNetx4_scratch_Grid/models
    training_state: /home/pjh2/ESRGAN/BasicSR/experiments/001_MSRResNetx4_scratch_Grid/training_state
    log: /home/pjh2/ESRGAN/BasicSR/experiments/001_MSRResNetx4_scratch_Grid
    val_images: /home/pjh2/ESRGAN/BasicSR/experiments/001_MSRResNetx4_scratch_Grid/val_images
  ]
  train:[
    lr_G: 0.0002
    lr_scheme: CosineAnnealingLR_Restart
    beta1: 0.9
    beta2: 0.99
    niter: 1000000
    warmup_iter: -1
    T_period: [250000, 250000, 250000, 250000]
    restarts: [250000, 500000, 750000]
    restart_weights: [1, 1, 1]
    eta_min: 1e-07
    pixel_criterion: l1
    pixel_weight: 1.0
    manual_seed: 10
    val_freq: 5000.0
  ]
  logger:[
    print_freq: 100
    save_checkpoint_freq: 5000.0
  ]
  is_train: True
  dist: False

19-07-03 21:28:11.638 - INFO: Random seed: 10
19-07-03 21:28:11.684 - INFO: Dataset [LQGTDataset - DIV2K] is created.
19-07-03 21:28:11.685 - INFO: Number of train images: 7,500, iters: 469
19-07-03 21:28:11.685 - INFO: Total epochs needed: 2133 for iters 1,000,000
19-07-03 21:28:11.685 - INFO: Dataset [LQGTDataset - val_set5] is created.
19-07-03 21:28:11.685 - INFO: Number of val images in [val_set5]: 12
19-07-03 21:28:13.386 - INFO: Network G structure: DataParallel - MSRResNet, with parameters: 1,517,571
19-07-03 21:28:13.386 - INFO: MSRResNet(
  (conv_first): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (recon_trunk): Sequential(
    (0): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (1): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (2): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (3): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (4): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (5): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (6): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (7): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (8): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (9): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (10): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (11): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (12): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (13): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (14): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (15): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
  )
  (upconv1): Conv2d(64, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (upconv2): Conv2d(64, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pixel_shuffle): PixelShuffle(upscale_factor=2)
  (HRconv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv_last): Conv2d(64, 3, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (lrelu): LeakyReLU(negative_slope=0.1, inplace)
)
19-07-03 21:28:13.386 - INFO: Model [SRModel] is created.
19-07-03 21:28:13.386 - INFO: Start training from epoch: 0, iter: 0
Traceback (most recent call last):
  File "train.py", line 232, in <module>
    main()
  File "train.py", line 152, in main
    for _, train_data in enumerate(train_loader):
  File "/home/pjh2/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/pjh2/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/pjh2/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/pjh2/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 63, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/pjh2/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 63, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/pjh2/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 43, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 24 and 0 in dimension 3 at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/TH/generic/THTensor.cpp:711

------------------------------------------------------------------------------------

I have seen all the issues including #110 and I think this is the problem of matching the dataset, but I have no idea what the problem is. Can you tell me what could be the problem and advise of each LR and HR sizes? Is my guess of the problem right in the first place?

p.s. I am very new to Deep Learning and your specific explanation will help a lot!! Thanks :)

**Comment by xinntao** [comment]
Did you use different settings for LR and HR images when you ran ` extract_subimgs_single.py`?
You should make sure that your data is OK.

**Comment by cui086** [comment]
is the problem solved? I countered same error.
