### ISSUE TITLE
Training Dataset Error 2

### ISSUE THREAD

**Issue by pjh1023** [xinntao/BasicSR#168]
My dataset is grayscale and therefore changed the color to GS instead of RGB. However, it produced this error

--------------------------------------------------------------------------------

export CUDA_VISIBLE_DEVICES=2
Disabled distributed training.
Path already exists. Rename it to [/home/pjh2/ESRGAN/BasicSR/experiments/001_MSRResNetx4_scratch_Grid_archived_190704-114410]
19-07-04 11:44:10.159 - INFO:   name: 001_MSRResNetx4_scratch_Grid
  use_tb_logger: True
  model: sr
  distortion: sr
  scale: 4
  gpu_ids: [2]
  datasets:[
    train:[
      name: DIV2K
      mode: LQGT
      dataroot_GT: /home/pjh2/ESRGAN/BasicSR/dataset2.0/train_x-rayOnly_verticalOnly/Sup_crop
      dataroot_LQ: /home/pjh2/ESRGAN/BasicSR/dataset2.0/train_x-rayOnly_verticalOnly/Grid_crop
      use_shuffle: True
      n_workers: 6
      batch_size: 16
      GT_size: 128
      use_flip: True
      use_rot: True
      color: GS
      phase: train
      scale: 4
      data_type: img
    ]
    val:[
      name: val_set5
      mode: LQGT
      dataroot_GT: /home/pjh2/ESRGAN/BasicSR/dataset2.0/val/Sup_crop
      dataroot_LQ: /home/pjh2/ESRGAN/BasicSR/dataset2.0/val/Grid_crop
      phase: val
      scale: 4
      data_type: img
    ]
  ]
  network_G:[
    which_model_G: MSRResNet
    in_nc: 3
    out_nc: 3
    nf: 64
    nb: 16
    upscale: 4
    scale: 4
  ]
  path:[
    pretrain_model_G: None
    strict_load: True
    resume_state: None
    root: /home/pjh2/ESRGAN/BasicSR
    experiments_root: /home/pjh2/ESRGAN/BasicSR/experiments/001_MSRResNetx4_scratch_Grid
    models: /home/pjh2/ESRGAN/BasicSR/experiments/001_MSRResNetx4_scratch_Grid/models
    training_state: /home/pjh2/ESRGAN/BasicSR/experiments/001_MSRResNetx4_scratch_Grid/training_state
    log: /home/pjh2/ESRGAN/BasicSR/experiments/001_MSRResNetx4_scratch_Grid
    val_images: /home/pjh2/ESRGAN/BasicSR/experiments/001_MSRResNetx4_scratch_Grid/val_images
  ]
  train:[
    lr_G: 0.0002
    lr_scheme: CosineAnnealingLR_Restart
    beta1: 0.9
    beta2: 0.99
    niter: 1000000
    warmup_iter: -1
    T_period: [250000, 250000, 250000, 250000]
    restarts: [250000, 500000, 750000]
    restart_weights: [1, 1, 1]
    eta_min: 1e-07
    pixel_criterion: l1
    pixel_weight: 1.0
    manual_seed: 10
    val_freq: 5000.0
  ]
  logger:[
    print_freq: 100
    save_checkpoint_freq: 5000.0
  ]
  is_train: True
  dist: False

19-07-04 11:44:10.351 - INFO: Random seed: 10
19-07-04 11:44:10.369 - INFO: Dataset [LQGTDataset - DIV2K] is created.
19-07-04 11:44:10.369 - INFO: Number of train images: 2,868, iters: 180
19-07-04 11:44:10.370 - INFO: Total epochs needed: 5556 for iters 1,000,000
19-07-04 11:44:10.370 - INFO: Dataset [LQGTDataset - val_set5] is created.
19-07-04 11:44:10.370 - INFO: Number of val images in [val_set5]: 120
19-07-04 11:44:12.065 - INFO: Network G structure: DataParallel - MSRResNet, with parameters: 1,517,571
19-07-04 11:44:12.065 - INFO: MSRResNet(
  (conv_first): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (recon_trunk): Sequential(
    (0): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (1): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (2): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (3): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (4): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (5): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (6): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (7): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (8): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (9): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (10): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (11): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (12): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (13): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (14): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (15): ResidualBlock_noBN(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
  )
  (upconv1): Conv2d(64, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (upconv2): Conv2d(64, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pixel_shuffle): PixelShuffle(upscale_factor=2)
  (HRconv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv_last): Conv2d(64, 3, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (lrelu): LeakyReLU(negative_slope=0.1, inplace)
)
19-07-04 11:44:12.065 - INFO: Model [SRModel] is created.
19-07-04 11:44:12.066 - INFO: Start training from epoch: 0, iter: 0
Traceback (most recent call last):
  File "train.py", line 232, in <module>
    main()
  File "train.py", line 152, in main
    for _, train_data in enumerate(train_loader):
  File "/home/pjh2/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/pjh2/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/pjh2/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/pjh2/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/pjh2/ESRGAN/BasicSR/codes/data/LQGT_dataset.py", line 130, in __getitem__
    img_GT = torch.from_numpy(np.ascontiguousarray(np.transpose(img_GT, (2, 0, 1)))).float()
ValueError: some of the strides of a given numpy array are negative. This is currently not supported, but will be added in future releases.

--------------------------------------------------------------------------------
Do you have any idea how to solve this problem?

**Comment by Master-P96** [comment]
Hi, I had the same problem, also with a grayscale dataset.
Changing line 132 and 133 in LQGT_dataset.py to:
`        img_GT = torch.from_numpy(np.ascontiguousarray(img_GT.transpose(2,0,1)[np.newaxis,:]).copy()).float()
        img_LQ = torch.from_numpy(np.ascontiguousarray(img_LQ.transpose(2,0,1)[np.newaxis,:]).copy()).float()`
solved the issue for me.

However after that I still get:
`RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 0 and 8 in dimension 4 at /pytorch/aten/src/TH/generic/THTensor.cpp:711
`
Even with the cropped DIV2K dataset I always get this issue.

**Comment by pjh1023** [comment]
@Master-P96 
I kind of went through the numpy array negative problem by reorganizing the dataset and changing some parameters
color: gray
in_nc: 1
out_nc: 1
but than it brings up **ValueError: not enough values to unpack (expected 3, got 2)**

when I applied color: RGB, in_nc:3, out_nc:3 it worked out fine with color images, but changing it to gray scale is quite hard :(

**Comment by Master-P96** [comment]
You could try to convert you gray images to RGB using ` img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)`

But in my case it returns: `19-07-04 12:11:27.463 - INFO: Start training from epoch: 0, iter: 0
Traceback (most recent call last):
  File "codes/train.py", line 232, in <module>
    main()
  File "codes/train.py", line 161, in main
    model.optimize_parameters(current_step)
  File "/gdrive/My Drive/Machine Learning/BasicSR/codes/models/SR_model.py", line 91, in optimize_parameters
    self.fake_H = self.netG(self.var_L)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/gdrive/My Drive/Machine Learning/BasicSR/codes/models/modules/SRResNet_arch.py", line 42, in forward
    fea = self.lrelu(self.conv_first(x))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight 64 3 3 3 0, but got 5-dimensional input of size [1, 1, 3, 32, 32] instead`

**Comment by xinntao** [comment]
@pjh1023 , first make sure that your dataset is OK. 
Check the img_GT and img_LQ shape, before `Line 130: img_GT = torch.from_numpy(np.ascontiguousarray(np.transpose(img_GT, (2, 0, 1)))).float()`

**Comment by xinntao** [comment]
@Master-P96 Your input have too much dims (got 5 instead of 4), please check whether the outputs of dataloader is OK.

**Comment by pjh1023** [comment]
@xinntao 
The shape of img_GT is (128, 128, 1) and img_LQ is (32, 32, 1)
I tried changing the GT_size in train_SRResNet.yml from 128 -> 64 and it worked only until iteration 5000. what does GT_size mean?? and is the shape above have any problem?
