### ISSUE TITLE
Do need train the  ESRAGN by my own

### ISSUE THREAD

**Issue by yanmenglu** [xinntao/BasicSR#172]
hi,@xinntao if I want to fine tune the ESRGAN by the new dataset (SR_raw). Could I need to retrain the PSNR_oriented model? Only train the D and G network, is that ok?

**Comment by xinntao** [comment]
I think you can finetune the provided trained model for faster convergence.

**Comment by yanmenglu** [comment]
yes, thx. I have finetuned the pre-trained model. the result is good. But ESRGAN is so big, Is there based GAN super-resolution model that can deploy on the device(like a smartphone)? could you give me some suggestion？

**Comment by xinntao** [comment]
You can search for it, for example, http://ai-benchmark.com/challenge.html

**Comment by yanmenglu** [comment]
ok, thx, you're so nice.

**Comment by 1810325** [comment]
@您好，看您用自己的数据重新训练了模型， 我现在也特别需要训练自己的模型，应为直接用作者的模型测试效果实在不好，但是我不知道该如何做，您能教我一下吗，人试提示将不盛感激，如果可以也剋加我微信love_qinging

**Comment by 1810325** [comment]
@yanmenglu 您好，看您用自己的数据重新训练了模型，我现在也特别需要训练自己的模型，应为直接用作者的模型测试效果实在不好，但是我不知道该如何做，您能教我一下吗，人试提示将不盛感激，如果可以也克加我微信love_qinging

**Comment by yanmenglu** [comment]
@1810325, the dataset is important , you can try to finetune the G network.
