### ISSUE TITLE
why the deeper BasicSr's  PI   is lower than your compet network?

### ISSUE THREAD

**Issue by zhuwanling** [xinntao/BasicSR#176]
为什么正式版版本更深的ESRGAN网络的PI值会高于比赛版本的PI值啦？

**Comment by zhuwanling** [comment]
Would  you mind  providing me your  codes_models_PIRM18SR_SuperSR version's trainer?
my email address: 1335206531@qq.com
thank you!

**Comment by xinntao** [comment]
Check out https://github.com/xinntao/ESRGAN/blob/master/QA.md
Higher PI values do not guarantee better visual quality. In this repo, we keep models with better visual quality.

You can modify the training codes from the current BasicSR repo. The modification has been described in the ESRGAN paper.
