### ISSUE TITLE
retrieve training procedure

### ISSUE THREAD

**Issue by t-martyniuk** [xinntao/BasicSR#18]
if I have stopped training due to some technical reasons, and I have previous versions of my model saved to the 'experiments' folder, how can I start not from the beginning again but from where I stopped the last time?

**Comment by jnjaby** [comment]
Yet we do not get this feature implemented for now. You can just save your model and information of the optimizer as a snapshot.

**Comment by xinntao** [comment]
Resuming is important. The codes should support this feature. 
We will add this later, (though it is not hard :flushed:).

**Comment by t-martyniuk** [comment]
can I add the lr_scheduler information to the state_dict manually? Which file in codes/ folder should I modify? @xinntao

**Comment by jnjaby** [comment]
@t-martyniuk Pass the optimizer information to `load_network` and `save_network` in `codes/models/base_model.py`.

**Comment by zzoon91** [comment]
Has anyone figured this out?

**Comment by mixtresh** [comment]
not save models in retrieve training procedure
----------------------------------------------------
Traceback (most recent call last):
  File "T:/BasicSR/codes/train.py", line 138, in <module>
    main()
  File "T:/BasicSR/codes/train.py", line 120, in main
    logger_val = logging.getLogger('val')  # validation logger
NameError: name 'logging' is not defined
----------------------------------------------------
i use conda on win 8.1
add  "import logging as logger" to train.py (logger not work. but training work) but not save model after validation.
logger not work on windows ? i search but not found for windows

**Comment by xinntao** [comment]
Thanks to @henrymai 's contribution, 
Have pulled a version of saving and loading training state. It saves the training states separately while saving the models. When resuming training, just pass a option with the name `resume_state`, like , `"resume_state": "../experiments/debug_001_RRDB_PSNR_x4_DIV2K/training_state/200.state"`
