### ISSUE TITLE
In your train，there is any rgb_mean for train data to average？

### ISSUE THREAD

**Issue by zhuwanling** [xinntao/BasicSR#180]

**Comment by zhuwanling** [comment]
你好！感谢你们的代码共享！
     GAN训练时由于生成器去掉了BN层，需要对输入训练数据做均值化吗？我看其他的基于edsr的GAN使用了        rgb_mean = (0.4488, 0.4371, 0.4040)，rgb_std = (1.0, 1.0, 1.0)进行处理。请问在你们的训练中使用了相应操作吗？

**Comment by xinntao** [comment]
No, we do not use these normalizations. It does not make differences from our previous experiments.

**Comment by zhuwanling** [comment]
Thanks for your reply.
Is there a weight for the discriminator?

**Comment by xinntao** [comment]
Did you mean the pre-trained discriminator?

**Comment by zhuwanling** [comment]
Yes

**Comment by zhuwanling** [comment]
Thank you, I found VGG
