### ISSUE TITLE
Training  about own data set

### ISSUE THREAD

**Issue by WANG-1173** [xinntao/BasicSR#184]
Hello, I am very lucky to see your share. I am a novice in the direction of target detection, and I am doing target detection for small targets such as cigarette butts and mobile phones.May I ask that I have some very vague data sets (people smoking and making phone calls). If I do target detection directly, I may not be able to identify them. Can I use the ESRGAN you provided to improve the definition and then continue target detection?I hope you can see my problems and give me some valuable advice. Thank you very much!

**Comment by xinntao** [comment]
You can have a try. 
And it is better to train/finetune both the detection and restoration parts together.

**Comment by WANG-1173** [comment]
You are really a kind scholar, so I would like to ask you, the video frames taken by the camera are relatively blurred and low resolution, so how to have HR and LR data for training when preparing data sets? It's getting late. Have a good dream and hope you have time to see my questions and get your reply.
