### ISSUE TITLE
Could you write a wiki about what the output numbers mean?

### ISSUE THREAD

**Issue by Audition-CSBlock** [xinntao/BasicSR#190]
Im totally confused at what this all means:
`lr:1.000e-04> l_g_pix: 3.8430e-03 l_g_fea: 1.9186e+00 l_g_gan: 5.7822e-02 l_d_real: 6.6850e-02 l_d_fake: 8.7473e-04 D_real: 1.4773e+01 D_fake: 3.2424e+00`

**Comment by xinntao** [comment]
lr: learning rate
l_g_pix: pixel loss (usually L1 or MSE loss) of the generator
l_g_fea: feature loss (perceptual loss, usually with VGG network) of the generator
l_g_gan: adversarial loss (GAN loss) of the generator
l_d_real: adversarial loss of the discriminator when input is the real data (GT)
l_d_fake: adversarial loss of the discriminator when input is the fake data (the outputs of the generator) D_real: the outputs of the discriminator when input is the real dada
D_fake: the outputs of the discriminator when input is the fake data

**Comment by Audition-CSBlock** [comment]
thanks!!
