### ISSUE TITLE
multi GPU training with ESRGAN error

### ISSUE THREAD

**Issue by llp1996** [xinntao/BasicSR#199]
i meet a question when use multi_GPU training ESRGAN,
error codes is
 ` File "/home/gpu/llp/BasicSR/codes/models/SRGAN_model.py", line 74, in __init__
    device_ids=[torch.cuda.current_device()])
`
error is 
"RuntimeError: replicas_[0].size() >= 1 ASSERT FAILED at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:53"

it seems that vgg loss dont support distribution training 
could you help me?

**Comment by xinntao** [comment]
Yes, the training of ESRGAN currently does not support multi-GPU training, due to the vgg loss.

**Comment by 1LOVESJohnny** [comment]
Hi @xinntao, I'm trying to train ESRGAN in a distributed training. Can I ask whether ESRGAN has been supported for multi-gpu training?

**Comment by xinntao** [comment]
@1LOVESJohnny 
ESRGAN has now supported multi-GPU training.  You can have a try. If you have any questions, please let me know. 

And the current learning scheme is developed for single GPU training. So for multi_GPU training, the optimal training scheme is to be determined.

**Comment by 1LOVESJohnny** [comment]
> @1LOVESJohnny
> ESRGAN has now supported multi-GPU training. You can have a try. If you have any questions, please let me know.
> 
> And the current learning scheme is developed for single GPU training. So for multi_GPU training, the optimal training scheme is to be determined.

Hi xintao, thanks for your reply.

I tried retraining ESRGAN with 'train_RRDBNet_PSNR_x4.yml' first, and it's been done successfully.
However, when I turned with 'train_ESRGAN_x4.yml', it would pump error message as below:

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512]] is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Seems like there exists some gradient computation is set as an inplace operation. I turned all the LeakyReLU op in rrdbnet_arch.py and discriminator_arch.py, but the error still shows up.

Have you ever met the problem?

**Comment by 1LOVESJohnny** [comment]
> > @1LOVESJohnny
> > ESRGAN has now supported multi-GPU training. You can have a try. If you have any questions, please let me know.
> > And the current learning scheme is developed for single GPU training. So for multi_GPU training, the optimal training scheme is to be determined.
> 
> Hi xintao, thanks for your reply.
> 
> I tried retraining ESRGAN with 'train_RRDBNet_PSNR_x4.yml' first, and it's been done successfully.
> However, when I turned with 'train_ESRGAN_x4.yml', it would pump error message as below:
> 
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512]] is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
> 
> Seems like there exists some gradient computation is set as an inplace operation. I turned all the LeakyReLU op in rrdbnet_arch.py and discriminator_arch.py, but the error still shows up.
> 
> Have you ever met the problem?

Besides, if I turned the mode into single GPU training, it will be running successfully with 'train_ESRGAN_x4.yml'.

**Comment by zhaowei11594** [comment]
> > > @1LOVESJohnny
> > > ESRGAN has now supported multi-GPU training. You can have a try. If you have any questions, please let me know.
> > > And the current learning scheme is developed for single GPU training. So for multi_GPU training, the optimal training scheme is to be determined.
> > 
> > 
> > Hi xintao, thanks for your reply.
> > I tried retraining ESRGAN with 'train_RRDBNet_PSNR_x4.yml' first, and it's been done successfully.
> > However, when I turned with 'train_ESRGAN_x4.yml', it would pump error message as below:
> > RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512]] is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
> > Seems like there exists some gradient computation is set as an inplace operation. I turned all the LeakyReLU op in rrdbnet_arch.py and discriminator_arch.py, but the error still shows up.
> > Have you ever met the problem?
> 
> Besides, if I turned the mode into single GPU training, it will be running successfully with 'train_ESRGAN_x4.yml'.
> 
> Expect for your reply. @xinntao

I have the same problem........

**Comment by xinntao** [comment]
@1LOVESJohnny @zhaowei11594 
I have updated the ESRGAN model, ref #278 

Please update the BasicSR repo to the newest version, and check whether the problem still exists. 

I have tested on my side, and everything is OK.
