### ISSUE TITLE
When I run the architecture.py alone, I get an error.

### ISSUE THREAD

**Issue by hust-lidelong** [xinntao/BasicSR#20]
The following error pops up：
   
 from . import block as B
ImportError: cannot import name 'block'

Thanks a lot!

**Comment by jnjaby** [comment]
Cuz you have not imported a parent module when running `python3 architecture.py`. Try to navigate to `/Path to project/codes` and run `python3 -m models.modules.architecture`.

BTW, why would you want to run the `architecture.py` alone?
