### ISSUE TITLE
Rescaling image from 0..1 to -1..1

### ISSUE THREAD

**Issue by t-martyniuk** [xinntao/BasicSR#21]
Is it possible to modify the code so the normalized pixels are in range -1..1?
I started to do it myself, but then stopped at

```
def rgb2ycbcr(img, only_y=True):
    '''same as matlab rgb2ycbcr
    only_y: only return Y channel
    Input:
        uint8, [0, 255]
        float, [0, 1]
    '''
```

won't it ruin the logic of the transformations?

**Comment by xinntao** [comment]
Hi @t-martyniuk 
It is better to rescale the images after converting to torch tensor, i.e., performing it after these lines:

https://github.com/xinntao/BasicSR/blob/71635757505ef113bfba029441a4e35e59994a86/codes/data/LRHR_dataset.py#L120-L121

**Comment by t-martyniuk** [comment]
should I substitute the line 66 in codes/utils/util.py as well? (function tensor2img)
`        img_np = (img_np * 255.0).round()
`
to
`        img_np = ((img_np + 1.) * 255.0 / 2.).round()
`

**Comment by xinntao** [comment]
@t-martyniuk 
You can set the argument min_max=(-1, 1) in 
https://github.com/xinntao/BasicSR/blob/71635757505ef113bfba029441a4e35e59994a86/codes/utils/util.py#L44-L51

**Comment by t-martyniuk** [comment]
ok, thank you very much

in the end, I changed only 
1) `min_max` parameter to `(-1, 1)` in **tensor2img** function
2) added 
`        img_HR = 2 * img_HR - 1
`
after  `img_HR = torch.from_numpy(np.ascontiguousarray(np.transpose(img_HR, (2, 0, 1)))).float() `
(the same for img_LR) in **LRHR_dataset.py**
(and in LR_dataset.py as well)

thank you for assistance!
