### ISSUE TITLE
about crop

### ISSUE THREAD

**Issue by splinter21** [xinntao/BasicSR#214]
是不是这么理解，lmdb先crop一次，然后根据yml文件里面设置的crop-size先从lmdb里面加载切完后的小图，然后再crop成设置的尺寸这样？
因为生成lmdb的时候crop有重叠部分，是不是lmdb处理完占用磁盘空间会额外多很多？但是因为相当于每次第二次crop，都是从更小的尺寸读进来的（而不是非常大的原图），所以磁盘读取速度需求会小很多，并且第二次crop的速度也会变快？

**Comment by xinntao** [comment]
Yes, you are right. 
The lmdb file will take up more disk space than the original images. The reason why we use lmdb is for faster training IO. The speedup is from two aspects: 1) reading the cropped sub-images is more efficient than directly reading the original large images; 2) lmdb itself will speed up the IO.
