### ISSUE TITLE
Error in your Wiki page

### ISSUE THREAD

**Issue by BostonLobster** [xinntao/BasicSR#218]
In the 'Color conversion in SR' chapter of your Wiki page, you wrote
> The cv2 package reads image in HxWxC, RGB channels. We can use the following two flags to convert between them.

However, according to the opencv documentation,
> the decoded images will have the channels stored in B G R order.

Could you please corret it to avoid some misleading?

**Comment by xinntao** [comment]
Yes, It is indeed BGR order.
I will corrent it. Thanks

**Comment by BostonLobster** [comment]
Also thanks for your contribution to community :)

**Comment by BostonLobster** [comment]
But I am also wondering do you make this mistake in your experiments for that chapter? Since I saw you are always prefer using cv2.COLOR_RGB2XXX. If so, does the conclusions in that chapter still hold?

**Comment by xinntao** [comment]
Oh, thanks, it is written a long time ago, I think I need to revise it later. 
I will check it later.
