### ISSUE TITLE
activation for RRDB_net

### ISSUE THREAD

**Issue by t-martyniuk** [xinntao/BasicSR#22]
the default activation_type you use in generator is 'leakyrelu'. have you tried doing as DCGAN paper suggests? they claim that one should use relu for all layers in generator except for the output where the tanh should be used.

**Comment by jnjaby** [comment]
In most cases, leakyrelu/prelu performs as good as, if not better than relu activation. The "dying ReLU" problem may occur when using a high learning rate. If you don't want to lower the learning rate, leaky relu/prelu should be good alternatives. Empirically, just feel free to use any activation_type you want to try.
