### ISSUE TITLE
some questions about code 

### ISSUE THREAD

**Issue by wl082013** [xinntao/BasicSR#220]
Hi xintao, 
I have two questions about the code 
1. input_ref = data['ref'] if 'ref' in data else data['GT']
            self.var_ref = input_ref.to(self.device)
what does ref mean here? Since if we need GT, so do we need to get another ref image as GT?
2.  You use RaD for training, so I am wondering is RaD alse fit for unsupervised training when Fake and Real are not paired, but FakeA and RealB .
Thank you so much for your help.
3. is it okay to make all LR with same size and HR pair with same size for training ? 
for example. LR: 256  and HR:256x4. 
Since I encountered some errors as shown _RuntimeError:_ invalid argument 0: Sizes of tensors must match except in dimension 0. Got 339 and 510 in dimension 2 at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/TH/generic/THTensor.cpp:711. 
I think that the size does not match.

**Comment by xinntao** [comment]
1. the ref for other uses. Now we do not need it. 
2. RaD is just a replacement of D in GAN. So if the unsupervised training task uses GAN, then RaD can also be used. 
3. It is OK to make all the training images have the same size. (actually, we use this setting with using cropped sub-images)
I think there is some mismatches in your prepared datasets.

**Comment by wl082013** [comment]
thanks a lot
