### ISSUE TITLE
Lower PSRN results

### ISSUE THREAD

**Issue by varun-intel** [xinntao/BasicSR#24]
When I test the model on the Set5 dataset with the pretrained weights in RRDB_PSNR_x4.pth, I get a psnr score of 15.0664 as opposed to 25+ reported in the paper. Do you know what the issue might be? I haven't modified the training code and ran the image preprocessing scripts as reported in the paper.

The only difference is that I used octave instead of matlab to run the downsampling script. The script produced uint16 images, which I converted to uint8 using the following code:

        img = cv2.imread(v, cv2.IMREAD_UNCHANGED)
        img = img.astype(np.float32)
        img = (img * 255.0 / 65535.0).round()
        img = img.astype(np.uint8)
        cv2.imwrite(v, img)

**Comment by jnjaby** [comment]
The PSNR socre 15 dB is extremely low. To check what induces the result, try using python downsampling method by setting `dataroot_LR` to `null` in the json file. If you get a testing score as high as reported in this way, then the result should be derived from octave or the data type conversion script. I have no idea if there is any difference between matlab's and octave's **bicubic interpolation function**.

**Comment by varun-intel** [comment]
Thanks, the issue was in the preprocessing.
