### ISSUE TITLE
Question: Parameters optimization order of the model D and G

### ISSUE THREAD

**Issue by xjw00654** [xinntao/BasicSR#251]
This part of the code looks hard to understand.   

In my understanding,  `(current_iter % self.net_d_iters == 0 and current_iter > self.net_d_init_iters)` means that we train `self.net_d_init_iters` iterations of the model G before we start train the model D, and we will skip to train the model D per `self.net_d_iters` iterations.    

If my understanding is not wrong, the optimization of  G and D seems reversed. We should put the D in the if-statement and leave the G optimization code outside.

Is that my mis-understanding :) ?

https://github.com/xinntao/BasicSR/blob/35ac620b51de437a529d73228276d8a50e1046d2/basicsr/models/srgan_model.py#L94:L137

```
if (current_iter % self.net_d_iters == 0
        and current_iter > self.net_d_init_iters):
    # pixel loss
    if self.cri_pix:
        l_g_pix = self.cri_pix(self.output, self.gt)
        l_g_total += l_g_pix
        loss_dict['l_g_pix'] = l_g_pix
    # perceptual loss
    if self.cri_perceptual:
        l_g_percep, l_g_style = self.cri_perceptual(
            self.output, self.gt)
        if l_g_percep is not None:
            l_g_total += l_g_percep
            loss_dict['l_g_percep'] = l_g_percep
        if l_g_style is not None:
            l_g_total += l_g_style
            loss_dict['l_g_style'] = l_g_style
    # gan loss
    fake_g_pred = self.net_d(self.output)
    l_g_gan = self.cri_gan(fake_g_pred, True, is_disc=False)
    l_g_total += l_g_gan
    loss_dict['l_g_gan'] = l_g_gan


    l_g_total.backward()
    self.optimizer_g.step()


# optimize net_d
for p in self.net_d.parameters():
    p.requires_grad = True


self.optimizer_d.zero_grad()
# real
real_d_pred = self.net_d(self.gt)
l_d_real = self.cri_gan(real_d_pred, True, is_disc=True)
loss_dict['l_d_real'] = l_d_real
loss_dict['out_d_real'] = torch.mean(real_d_pred.detach())
l_d_real.backward()
# fake
fake_d_pred = self.net_d(self.output.detach())
l_d_fake = self.cri_gan(fake_d_pred, False, is_disc=True)
loss_dict['l_d_fake'] = l_d_fake
loss_dict['out_d_fake'] = torch.mean(fake_d_pred.detach())
l_d_fake.backward()
self.optimizer_d.step()      
```

**Comment by xinntao** [comment]
@xjw00654 
Maybe you are misunderstanding. 

`(current_iter % self.net_d_iters == 0 and current_iter > self.net_d_init_iters)` means that 
1. we train `net_d_iters` times for D and one time for G, which is used in WGAN. 
2. Before we train G, we train `net_d_init_iters` times D, which is reflected by its name d_init_iters. This is usually used in WGAN.

**Comment by xjw00654** [comment]
Great tks !!
