### ISSUE TITLE
Test SRRestnet ——KeyError: Caught KeyError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by liyinong0328** [xinntao/BasicSR#264]
Hi @xinntao
Thank you for your repo ! I have some problems when I try to test the SRResNet.
I download the lasted code from github and download a pre-trained SRResNet model. When I ran the command:
 `python basicsr/test.py -opt options/test/SRResNet_SRGAN/test_MSRResNet_x4.yml` 
to test the model there is an error:

`Traceback (most recent call last):`
`File "basicsr/test.py", line 68, in <module>`
`main()`
`File "basicsr/test.py", line 64, in main`
`save_img=opt['val']['save_img'])`
`File "/home/BasicSR/basicsr/models/base_model.py", line 56, in validation`
`save_img)`
` File "/home/BasicSR/basicsr/models/sr_model.py", line 137, in nondist_validation`
`for idx, val_data in enumerate(dataloader):`
`File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__`
`  return self._process_data(data)`
`File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data`
`data.reraise()`
`File "/root/miniconda3/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise`
`raise self.exc_type(msg)`
`KeyError: Caught KeyError in DataLoader worker process 0.`
`Original Traceback (most recent call last):`
`File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop`
` data = fetcher.fetch(index)`
`File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch`
`data = [self.dataset[idx] for idx in possibly_batched_index]`
` File "/root/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>`
`data = [self.dataset[idx] for idx in possibly_batched_index]`
` File "/home/BasicSR/basicsr/data/paired_image_dataset.py", line 75, in __getitem__`
` gt_size = self.opt['gt_size']`
`KeyError: 'gt_size'`
I think there is something wrong with the DataLoader but I can't find it, waiting and thank you for your reply.

**Comment by liyinong0328** [comment]
I set the value of gt_size to 128 by myself in "basics/data/paired_image_dataset" instead of the original  
`gt_size = self.opt[gt_size]`
but I think this is not the best solution

**Comment by xinntao** [comment]
Hi @liyinong0328 
Thanks for reporting this bug!
This bug is because we use training keys during testing. I have fixed in the newest master branch. 
Thanks ~
