### ISSUE TITLE
What dataset did you use to train RRDB-ESRGAN model?

### ISSUE THREAD

**Issue by endofmovie108** [xinntao/BasicSR#266]
I'm very inspired by the sharing of your research results. Thanks a lot.
I have a few questions.

1. I have an information about RRDB-PSNR model's (uploaded) trained dataset, which is DF2K, with 192x192 GT-patch size right?

2. I have a question on your uploaded final model  RRDB-ESRGAN model's trained dataset. Did you trained with (load pre-trained RRDB-PSNR(DF2K)) DF2K + OST with 128x128 GT-patch size?

**Comment by xinntao** [comment]
1. DF2K dataset with training patch size 128 x128
2. DF2K + OST dataset with training patch size 128 x128
