### ISSUE TITLE
关于SRGANModel输入大小的问题

### ISSUE THREAD

**Issue by gudandenanhaier** [xinntao/BasicSR#275]
![image](https://user-images.githubusercontent.com/13115947/91650278-03f8c480-eab0-11ea-9ea1-f36acd298ecf.png)
在SRGAN训练过程中，计算GANLoss时，self.net_d网络的输入大小只能是128x128的，但是此处self.output的大小一定是128x128吗？

**Comment by xinntao** [comment]
@gudandenanhaier 在训练的过程中,  我们都使用 128x128的进行训练. 在测试的时候, D是不用的, 而G是fully convolution的, 所以可以接受任意size的input

**Comment by Stemmaker** [comment]
你好，请问一下128*128训练的模型用于其他任意size的图片做高分辨时，模型的精度会有影响吗
