### ISSUE TITLE
cannot import name 'deform_conv_ext'

### ISSUE THREAD

**Issue by penghusile** [xinntao/BasicSR#280]
/BasicSR/basicsr/models/ops/dcn/deform_conv.py", line 9, in <module>
    from . import deform_conv_ext
I find this is a cpp file ,how to import it?

**Comment by elezine** [comment]
I also have the same issue!

**Comment by xinntao** [comment]
@penghusile @elezine 
Did you run `python setup.py develop` before import it?

**Comment by elezine** [comment]
@xinntao This solved it! Thanks so much, really appreciate your work.

**Comment by penghusile** [comment]
@xinntao  I try to ran this file but system reported my gcc version is too low. My system gcc version is 4.8.5 and Anaconda gcc version is 7.3.0. I ran it in anaconda. Why does it use the system gcc?

**Comment by xinntao** [comment]
> @xinntao I try to ran this file but system reported my gcc version is too low. My system gcc version is 4.8.5 and Anaconda gcc version is 7.3.0. I ran it in anaconda. Why does it use the system gcc?

@penghusile when compiling, it uses the system gcc. Try to upgrade your gcc version
