### ISSUE TITLE
can i generate bicubic img by using python?

### ISSUE THREAD

**Issue by ruby1ring** [xinntao/BasicSR#284]
can i generate bicubic img by using a py flie?
i can not find a py flie to generate bicubic img.only a matlab flie to generate?

**Comment by xinntao** [comment]
Hi @ruby1ring 
The python interface of MATLAB bicubic function is not updated. 
If you want to use, you can find the script in the [v0.1 branch](https://github.com/xinntao/BasicSR/tree/v0.1):
 https://github.com/xinntao/BasicSR/blob/v0.1/codes/scripts/generate_mod_LR_bic.py

We will sort out these codes and add it this new repo later :-)

**Comment by ruby1ring** [comment]
I really appreciate it.and an other question,Why can't we achieve the expected results by using default option of EDSR ?

**Comment by ruby1ring** [comment]
> Hi @ruby1ring
> The python interface of MATLAB bicubic function is not updated.
> If you want to use, you can find the script in the [v0.1 branch](https://github.com/xinntao/BasicSR/tree/v0.1):
> https://github.com/xinntao/BasicSR/blob/v0.1/codes/scripts/generate_mod_LR_bic.py
> 
> We will sort out these codes and add it this new repo later :-)

I really appreciate it.and an other question,Why can't we achieve the expected results by using default option of EDSR ?

**Comment by ruby1ring** [comment]
> Hi @ruby1ring
> The python interface of MATLAB bicubic function is not updated.
> If you want to use, you can find the script in the [v0.1 branch](https://github.com/xinntao/BasicSR/tree/v0.1):
> https://github.com/xinntao/BasicSR/blob/v0.1/codes/scripts/generate_mod_LR_bic.py
> 
> We will sort out these codes and add it this new repo later :-)

I really appreciate it.And an other question,DId you test the model to achieve the baseline results PSNR  by using default option of EDSR ?

**Comment by xinntao** [comment]
@ruby1ring 
For EDSR, I have tested. 
1. the official models (https://drive.google.com/drive/folders/15DgDtfaLASQ3iAPJEVHQF49g9msexECG) are transferred from the official EDSR repo. They could produce the same results as the official EDSR repo.
2. I have also trained with BasicSR, you can find the models and logs (https://drive.google.com/drive/folders/1XN4WXKJ53KQ0Cu0Yv-uCt8DZWq6uufaP) and online wandb curves (https://app.wandb.ai/xintao/basicsr). It can almost reproduce with a very slight difference.

**Comment by ruby1ring** [comment]
> @ruby1ring
> For EDSR, I have tested.
> 
> 1. the official models (https://drive.google.com/drive/folders/15DgDtfaLASQ3iAPJEVHQF49g9msexECG) are transferred from the official EDSR repo. They could produce the same results as the official EDSR repo.
> 2. I have also trained with BasicSR, you can find the models and logs (https://drive.google.com/drive/folders/1XN4WXKJ53KQ0Cu0Yv-uCt8DZWq6uufaP) and online wandb curves (https://app.wandb.ai/xintao/basicsr). It can almost reproduce with a very slight difference.

for example:ESDR lx4 default option(train set:div2k vaild set: set5 ). In paper ,the psnr is 32.62,but in your wandb,the psnr is30.47.Sorry,I am first reprodeuce SR domain,this gap is very sligth differenece in SR?

**Comment by ruby1ring** [comment]
> @ruby1ring
> For EDSR, I have tested.
> 
> 1. the official models (https://drive.google.com/drive/folders/15DgDtfaLASQ3iAPJEVHQF49g9msexECG) are transferred from the official EDSR repo. They could produce the same results as the official EDSR repo.
> 2. I have also trained with BasicSR, you can find the models and logs (https://drive.google.com/drive/folders/1XN4WXKJ53KQ0Cu0Yv-uCt8DZWq6uufaP) and online wandb curves (https://app.wandb.ai/xintao/basicsr). It can almost reproduce with a very slight difference.

for example:EDSR_lx4 default option(train set:div2k vaild set: set5 ). In paper ,the psnr is 32.62,but in your wandb,the psnr is30.47.Sorry,I am first reprodeuce SR domain,this  gap is very sligth differenece in SR?

**Comment by xinntao** [comment]
@ruby1ring 

There are two versions of results in the paper: EDSR and EDSR+, please note that EDSR+ uses tests with geometric self-ensemble techniques. So, for fair comparisons, we should compare with EDSR, which is 30,46 (BasicSR reimplementation is 30.47) (You can also use tests with geometric self-ensemble techniques for our trained models.)

![image](https://user-images.githubusercontent.com/17445847/92549667-690ca100-f28c-11ea-994b-36c7ddd4dc70.png)

The following is a detailed comparison, for your reference.

![image](https://user-images.githubusercontent.com/17445847/92549933-fea83080-f28c-11ea-9f11-3aa6c986b921.png)

**Comment by ruby1ring** [comment]
> @ruby1ring
> 
> There are two versions of results in the paper: EDSR and EDSR+, please note that EDSR+ uses tests with geometric self-ensemble techniques. So, for fair comparisons, we should compare with EDSR, which is 30,46 (BasicSR reimplementation is 30.47) (You can also use tests with geometric self-ensemble techniques for our trained models.)
> 
> ![image](https://user-images.githubusercontent.com/17445847/92549667-690ca100-f28c-11ea-994b-36c7ddd4dc70.png)
> 
> The following is a detailed comparison, for your reference.
> 
> ![image](https://user-images.githubusercontent.com/17445847/92549933-fea83080-f28c-11ea-9f11-3aa6c986b921.png)

i mean EDSR_lx4 three result: paper result(32.46) ,reproduced Models(30.4718),official releassed model(30.5499)
there are big gap between the first one and other？why？

**Comment by xinntao** [comment]
I think the gap is reasonable, you can try other runs, the result can vary.

**Comment by ruby1ring** [comment]
> 我认为差距是合理的，您可以尝试其他运行，结果可能会有所不同。
> 
> 顺便说一句，官方仓库在训练期间选择最佳模型，而BasicSR使用最新模型。这也是差异的根源。

Thank you a lot for your assistance.I check the psnr of BasicSR EDSR lx4.The peak of psnr is 30.557.compare with 32.46 psnr in paper,There are 1.9 psnr point gap.so maybe is not main cause?maybe we need some other train trick?

**Comment by ruby1ring** [comment]
> I think the gap is reasonable, you can try other runs, the result can vary.
> 
> BTW, the official repo selects the best model during training, while BasicSR uses the latest model. This is also a source of difference.

oh,you mean the reasons for this gap is Randomness? if i train model a lot of times,maybe,can i get the paper result?

**Comment by xinntao** [comment]
@ruby1ring 

OK, I think I have misunderstood something. 
The paper results are tested on the Y channel instead of the RGB channel.  You can also test with the Y channel and get similar results.

**Comment by xinntao** [comment]
You can also test with the Y channel with BasicSR, and You can get similar results as paper show.

**Comment by ruby1ring** [comment]
> You can also test with the Y channel with BasicSR, and You can get similar results as paper show.

I am very grateful for your help.Thank you very much for taking the whole morning to answer my question.I totally understand.hope basicSR get better and better.(ノ`⊿´)ノ

**Comment by xinntao** [comment]
@ruby1ring 
Pleasure~
Glad that you use and like BasicSR. Welcome report bugs and tell more people about it! 😄
