### ISSUE TITLE
Inference batch size

### ISSUE THREAD

**Issue by pepinu** [xinntao/BasicSR#288]
For the EDVR model, is there any particular reason the inference batch size is fixed to 1?

If I happen to set batch size for the test to a larger value, would this impact the PSNR, or is this not tested?

As for the VRAM usage in the case of the REDS dataset, I could easily fit 32 samples on Tesla T4.

**Comment by xinntao** [comment]
The current testing script for EDVR sets the batch size to 1. 
You can modify the testing script to support larger batch size ~
