### ISSUE TITLE
Pre-trained PSNR-oriented model

### ISSUE THREAD

**Issue by elezine** [xinntao/BasicSR#289]
I would like to train a PSNR-oriented model (4x upsampling) with my own imagery to use as a pre-trained model for ESRGAN instead of using a DF2k pre-trained model (such as ESRGAN_PSNR_SRx4_DF2K_official-150ff491.pth available in the model zoo). How was ESRGAN_PSNR_SRx4_DF2K_official-150ff491.pth trained? Should I train from scratch with RRDBNet_PSNR_x4 or MSRResNet_x4? Thank you so much! Your work is amazing.

**Comment by xinntao** [comment]
Sorry for the late reply. You ccan train it with the configration file: 

https://github.com/xinntao/BasicSR/blob/b25509ec29a38ae8ed8f8d5e5873d3e719d2a33a/options/train/ESRGAN/train_RRDBNet_PSNR_x4.yml#L1-L12

**Comment by elezine** [comment]
No worries! Thank you.
