### ISSUE TITLE
Bug in calculating PSNR

### ISSUE THREAD

**Issue by YujiePan** [xinntao/BasicSR#293]
I am using the code with latest commit `b25509ec29a38ae8ed8f8d5e5873d3e719d2a33a` .

See: `./basicsr/metrics/pnsr_ssim.py` :
https://github.com/xinntao/BasicSR/blob/b25509ec29a38ae8ed8f8d5e5873d3e719d2a33a/basicsr/metrics/psnr_ssim.py#L46

The `calculate_psnr` function receives two `numpy.uint8` images, but the substraction operation should be conducted on two `numpy.float` variables. Clearly the calculated MSE by current codes is smaller than desired. 

I found this bug when trying EDVR-M-woTSA on REDS SR datasets, and the averaged PSNR on REDS4 was unexpectedly >33 even with only 20k iterations.

**Comment by xinntao** [comment]
Thanks for reporting this bug. It is introduced from this commit https://github.com/xinntao/BasicSR/commit/e55bac48676273f9f01156cae723304c59760284 (in file  basicsr/utils/util.py )

I have fixed it now. Thanks very much: 🚀
