### ISSUE TITLE
关于超分辨率测试集

### ISSUE THREAD

**Issue by lightfate** [xinntao/BasicSR#294]
你好，关于你在DatasetPreparation_CN.md中的超分辨率测试集(set5、set14、manga109、historical、BSDS100)，除了set5和set14以外，其他3个都只有HR的图片，如果要得到模型在这些测试集上的PSNR，是不是得自己把这些图片通过bicubic的算化缩小x2、x3、x4作为LR测试集？还是说官方有提供LR数据集？

**Comment by xinntao** [comment]
They do not have official LR datasets. Usually, we use the MATLAB bicubic function to generate LR images.

**Comment by lightfate** [comment]
thanks~
