### ISSUE TITLE
Bugs in Lint(#297) 'do not use list in arguments'

### ISSUE THREAD

**Issue by WMCh** [xinntao/BasicSR#298]
Hi, comma in one-element tuples may be missing in `lr_scheduler.py`:
line 23-24:
```
restarts=(0,),
restart_weights=(1,),
```
line 93:
```
restart_weights=(1,),
```

**Comment by xinntao** [comment]
@WMCh  Thanks, I have fixed and it is OK in the master branch. Thanks!
