### ISSUE TITLE
Where is the option folder? 

### ISSUE THREAD

**Issue by pkmonster** [xinntao/BasicSR#30]
Sorry, I didn't find the options folder as well as config.json. Could you please check again ? Thank you

**Comment by xinntao** [comment]
Hi,  pkmonster, 

I can see the [`options` folder](https://github.com/xinntao/BasicSR/tree/master/codes/options).

**Comment by pkmonster** [comment]
Hi xinntao, 

Thank you so much for quickly reply. I've found it. 

I just want to ask you about the evaluation on testing set,especially "Set14"
In the model, the input is 3 channels, but in Set14, we have 1 image with 1 channel. How can we input that image to our model ? Thank you ?
