### ISSUE TITLE
Where to Download DIV2K Set 14?

### ISSUE THREAD

**Issue by athenawisdoms** [xinntao/BasicSR#302]
When trying to adjust the settings in [`train_ESRGAN_x4.yml`](https://github.com/xinntao/BasicSR/blob/master/options/train/ESRGAN/train_ESRGAN_x4.yml), I notice the option `dataroot_gt` and `dataroot_lq` with values `datasets/Set14/GTmod12` and `datasets/Set14/LRbicx4`. 

Where can we download these validation datasets? I do not see "Set14" available for download at https://data.vision.ee.ethz.ch/cvl/DIV2K/

Also, do we need to process/prepare the "Set14" images using `extract_subimages.py` before using them for training/validation?

Thanks!

**Comment by yera217** [comment]
Did you try this?
https://github.com/xinntao/BasicSR/blob/master/docs/DatasetPreparation.md#Common-Image-SR-Datasets

**Comment by xinntao** [comment]
@athenawisdoms  https://drive.google.com/drive/folders/1pRmhEmmY-tPF7uH8DuVthfHoApZWJ1QU for Set 14
 There is no need to preprocess for validation datasets (Set14 is a validation/testing dataset.)

@yera217  Thanks!
