### ISSUE TITLE
Why does changing the ESRGAN network framework invalid？

### ISSUE THREAD

**Issue by difcreate** [xinntao/BasicSR#303]
I modified the network architecture in the file rrdbnet_arch.py, 　but the original network frame structure is still displayed every time I run it, and the modification is invalid. For example, I removed a layer of upsampling, but the scaling  is still 4, not 2.

**Comment by xinntao** [comment]
Did you have several BasicSR repo? or did you run  python setup.py develop?

**Comment by difcreate** [comment]
thanks! 
I solved the problem by re-running set.py to establish the environment after changing the network structure.
