### ISSUE TITLE
The command ‘python setup.py install --no_cuda_ext’didn't seem to work

### ISSUE THREAD

**Issue by wytcsuch** [xinntao/BasicSR#307]
```
(pytorch) root@vm2020091000029-vm-bc647d878-nw6vj:/wytdata/BasicSR-master# python setup.py install --no_cuda_ext
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --no_cuda_ext not recognized
```

**Comment by xinntao** [comment]
Try to use `python setup.py develop --no_cuda_ext`?

I test in Google Colab , it is OK. 

https://colab.research.google.com/drive/1JQScYICvEC3VqaabLu-lxvq9h7kSV1ML?usp=sharing

**Comment by xinntao** [comment]
I also test `python setup.py install --no_cuda_ext` and it is OK in colab

**Comment by SB2020-eye** [comment]
Hi. I'm getting this same error, using colab.

```error: option --no_cuda_ext not recognized```

This is the result whether I run it "as is":

```
# Install BasicSR without cuda extentions
!python setup.py develop --no_cuda_ext
```

or changing "develop" to "install":

```
# Install BasicSR without cuda extentions
!python setup.py install --no_cuda_ext
```

Can anyone suggest a fix or workaround? (I'm a noob.)

**Comment by xinntao** [comment]
@SB2020-eye  Hi, as I have updated BasicSR, so the cmd should be updated:

'!python setup.py develop'

I have updated the colab, you can have a try.

If you still encounter this issue, please let me know.
