### ISSUE TITLE
Why does the PSNR keeps decreasing when training ESRGAN?

### ISSUE THREAD

**Issue by lightfate** [xinntao/BasicSR#308]
Hello, first of all thank you for your open source project。
I encountered a problem when I tried to reproduce your results about ESRGAN。
Mydataset is DF2K 
1. First I trained a RRDBNET_X4 model  from scratch;  After 220k iters, I get 27.0 PSNR-RGB(28.8 PSNR-Y) on set14 (Green Curve ). 
2. Then I use that model to train ESRGAN, but the psnr keeps decreasing over time(Black Curve), this problem also happened on set5.

so there are some questions about this:
1. Is this situation normal？ Did i do something wrong？
2. the 28.99 PSNR-Y in your paper  is your RRDBNET's result or ESRGAN's result? 
3. What's your  PSNR curve of ESRGAN like？ What's your final PSNR-Y of ESRGAN on set14?

![image](https://user-images.githubusercontent.com/41222646/96012443-b0331680-0e76-11eb-881a-2947de26455c.png)

![image](https://user-images.githubusercontent.com/41222646/96011793-f89e0480-0e75-11eb-98ea-105048ac4c22.png)

**Comment by xinntao** [comment]
Hi @lightfate 
1. GAN-based models such as SRGAN, ESRGAN produces lower PSNR values. And PSNR is not a good metric (reflecting the visual quality) for GAN0-based models. So when you train ESRGAN, the PSNR will decrease.
2. In the paper, RRDB  indicates the model trained with L1/L2 loss, not the gan loss. 
3. You can obtain ESRGAN training curves in https://wandb.ai/xintao/basicsr/runs/1qezt05j?workspace=user-xintao
note that the dataset is DIV2K

**Comment by lightfate** [comment]
Thank you～
