### ISSUE TITLE
Error detected in CudnnBatchNormBackward

### ISSUE THREAD

**Issue by RyanXingQL** [xinntao/BasicSR#322]
作者您好！

我仿照您的最新代码写了ESRGAN，但在多GPU时仍然会报错：
![image](https://user-images.githubusercontent.com/34084019/97868600-f5968580-1d4a-11eb-94c7-2610cf5edd40.png)

我用torch.autograd.set_detect_anomaly(True)查询错误，发现是BN的问题。难道是BN内部存在inplace变量的问题吗？

我的discriminator loss写法：
```
optim_d.zero_grad()

gt_pred = model_d(gt_data)  # grads only relate to d
enh_pred = model_d(enhanced_data).detach()  # detach, as constant
loss_gt_half = gan_loss_func(gt_pred - torch.mean(enh_pred), True) * 0.5
loss_gt_half.backward()

enh_pred = model_d(enhanced_data.detach())
loss_enh_half = gan_loss_func(enh_pred - torch.mean(gt_pred.detach()), False) * 0.5
loss_enh_half.backward()

optim_d.step()
```

错误发生在`loss_gt_half.backward()`这一步。

谢谢指教！

**Comment by xinntao** [comment]
for relativistic gan in multiGPU, please refer to https://github.com/xinntao/BasicSR/blob/58d75552c1027de843a9d3f4a94987d137fbd522/basicsr/models/esrgan_model.py#L69-L82

If you look inside your codes, you could find that BN layers in net D have forwards twice and then backwards, which cause the issue.

**Comment by RyanXingQL** [comment]
Thanks! I change the order of `gt_pred` and `enh_pred` in my code and solve the problem!
