### ISSUE TITLE
Something went wrong when I executed 'python setup.py develop'

### ISSUE THREAD

**Issue by KeqiWangSXuniversity** [xinntao/BasicSR#325]
basicsr/models/ops/dcn/src/deform_conv_cuda.cpp: In function ‘void modulated_deform_conv_cuda_backward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int, bool)’:
basicsr/models/ops/dcn/src/deform_conv_cuda.cpp:579:73: error: ‘TORCH_CHECK’ was not declared in this scope
   TORCH_CHECK(input.is_contiguous(), "input tensor has to be contiguous");

**Comment by xinntao** [comment]
What is your pytorch and cuda version?

**Comment by KeqiWangSXuniversity** [comment]
pytorch:1.1.0
cuda:9.0

**Comment by KeqiWangSXuniversity** [comment]
> 
> 
> What is your pytorch and cuda version?

pytorch:1.1.0
cuda:9.0

**Comment by xinntao** [comment]
@KeqiWangSXuniversity 
It currently support Pytorch >=1.3

Please see the requirements.
