### ISSUE TITLE
Pre-trained weights for TOFlow

### ISSUE THREAD

**Issue by jinsuyoo** [xinntao/BasicSR#328]
Hi xinntao!

Thanks for maintaining good repo.
I am wondering whether you can provide the pre-trained weights on TOFlow?
If I'm correct, It seems like testing the model is already done. 
 
Again, thank you!

**Comment by xinntao** [comment]
@jinsuyoo 
Hi, 
Yes, I have converted TOFlow model before, but since I have updated BasicSR, the model also needs to be updated.

I am busy these  days,  will do this convert after Nov 17, 
Will let you know here after it is ready. 
Thanks. 

- [ ] Add official TOFlow model.

**Comment by jndeng** [comment]
@xinntao @jinsuyoo 
Hey guys, I've converted TOFlow weights from MMEditing to BasicSR. Test result on Vid4 match that reported in the Model Zoo. I've uploaded it on google drive [here](https://drive.google.com/file/d/1W5Gg9sDC7AJkFf0IizZykAHOhaZ175iR/view?usp=sharing).

And to use the weights, [`tof_arch.py`](https://github.com/xinntao/BasicSR/blob/master/basicsr/models/archs/tof_arch.py) needs a little update.
The first four Conv layers in [`self.basic_module`](https://github.com/xinntao/BasicSR/blob/1464d8e5c1ab27c12285c21771c2fc5a71382d32/basicsr/models/archs/tof_arch.py#L19-L42) should be set to bias=False.

**Comment by jinsuyoo** [comment]
@jndeng 
Wonderful! 
many thanks :)
