### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by Jing25** [xinntao/BasicSR#33]
I'm new to this. I'm curious that when I train the model, I got G.pth and D.pth. While in the option files, e.g., test_esrgan.json, you only provide option for "pretrain_model_G", then how about model_D? What if I want to use pretrained model_D?

**Comment by Jing25** [comment]
BTW, after I trained ESRGAN, I got the latest_G and latest_D. When I do the test, do I change "pretrain_model_G", in test_esrgan.json to latest_G?

**Comment by jnjaby** [comment]
For testing, you only need to generate an SR image and the score of network_D is not required.

**Comment by xinntao** [comment]
Hi @Jing25,
As jnjaby said, when testing, the model_D is unnecessary. If you want to get the outputs of D, you can add another option like "pretrain_model_D", but you also need to modify the test codes in 
https://github.com/xinntao/BasicSR/blob/c345d635cdf079e39dcf0279c899d1dbe852e95c/codes/models/SRRaGAN_model.py#L188-L192

When you testing, the pretrain_model_G could be any model you want to use. You could use latest_G or models in other iterations.

**Comment by ackbar03** [comment]
Hi, 

why do you say we need to modify the test codes

[https://github.com/xinntao/BasicSR/blob/c345d635cdf079e39dcf0279c899d1dbe852e95c/codes/models/SRRaGAN_model.py#L188-L192](url)

? Did you highlight the wrong section by accident? I assume you mean

[https://github.com/xinntao/BasicSR/blob/c345d635cdf079e39dcf0279c899d1dbe852e95c/codes/models/SRRaGAN_model.py#L234](url)

but even then it looks fine to me?

**Comment by xinntao** [comment]
Hi @ackbar03 
What I mean is that if one wants to get the outputs of D during testing, he may need to modify the test codes in the `def test(self): ` function. 

We usually do not need to output D and during testing, we only need `pretrain_model_G`.
