### ISSUE TITLE
Cannot open some datasets，while others is ok

### ISSUE THREAD

**Issue by qwerdf4** [xinntao/BasicSR#335]
File "BasicSR\BasicSR-master\basicsr\utils\file_client.py", line 74, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/DIV2K/DIV2K_train_LR_bicubic/X4_sub\\0553.png'

**Comment by xinntao** [comment]
Check the corresponding file to see whether it is OK or corrupted.
