### ISSUE TITLE
Q：create lmdb Error：ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by CrystalWong2** [xinntao/BasicSR#34]
First time I ran the creat_lmdb, it occured that ZeroDivisionError: float division by zero. 

![image](https://user-images.githubusercontent.com/16526692/48938329-de8a6e80-ef4b-11e8-849e-aef25012291f.png)

if I change the code like that:
![image](https://user-images.githubusercontent.com/16526692/48938442-2b6e4500-ef4c-11e8-9257-28bd81b5b058.png)

It can read, but fail to write. The error is the same... But!!! It produce the lmdb file even my cmd told me that it had error.So anyone help me please....

**Comment by xinntao** [comment]
Hi @CrystalWong2 
Check whether image path (v) and img are OK.

**Comment by CrystalWong2** [comment]
Thank you so much

**Comment by jilner** [comment]
I have the same question,hou to resolve it?  thank you very much
