### ISSUE TITLE
will the GFP-GAN joined into BasicSR family?

### ISSUE THREAD

**Issue by zhangyunming** [xinntao/BasicSR#356]
hi, xintao 

I am reading your new paper  'Towards Real-World Blind Face Restoration with Generative Facial Prior', the relsut is so amazing ,  so the code of GFP-GAN will join into BasicSR?  wait in hope！

**Comment by xinntao** [comment]
Hi @zhangyunming 
Thanks for your interest in our work. GFP-GAN will be added into BasicSR when it is ready.

**Comment by ofirkris** [comment]
Amazing!
Can you estimate when you will release the full pipeline
