### ISSUE TITLE
Windows run SRGAN model

### ISSUE THREAD

**Issue by CrystalWong2** [xinntao/BasicSR#36]
When I trained my own model using my database, it worked well. But unfortunately if I ran the code in windows anaconda，it showed the error like this:
![image](https://user-images.githubusercontent.com/16526692/49072676-b06a9e80-f26b-11e8-8964-7581416d3b37.png)

It maybe some problem about pytorch multiprocessing in windows.
If someone knows how to solve it,pls help! Thx~

**Comment by jnjaby** [comment]
This code should work with Python 3.3+ and Pytorch 0.4.0 on Ubuntu.
You can search for more information on Pytorch-windows. Windows anaconda is your own adventure.

**Comment by CrystalWong2** [comment]
@jnjaby Thanks for your suggestion~

**Comment by CrystalWong2** [comment]
> @CrystalWong2 did you resolve this? I'm running vanilla Python 3.6 (and latest PyTorch) on Windows and ran into the same error but when training ESRGAN.

No, just like I wrote above, maybe some problem about pytorch multiprocessing in windows. I searched a lot, so I just think it may be the little bug of pytorch in windows...It can work well in Ubuntu...I recommend you change the platform and try..

**Comment by CrystalWong2** [comment]
@Fironet No, just like I wrote above, maybe some problem about pytorch multiprocessing in windows. I searched a lot, so I just think it may be the little bug of pytorch in windows...It can work well in Ubuntu...I recommend you change the platform and try..

**Comment by Titaniumtown** [comment]
@CrystalWong2 I was wondering if you could give me a copy of your "test_esrgan.json" and "train_esrgan.json" in "codes/options/test and "codes/options/train" respectively? I am trying to find out how to put paths in because it keeps spitting out errors about the backslashes found in windows folder paths.
