### ISSUE TITLE
Can't find 'basicsr.version'

### ISSUE THREAD

**Issue by ChocolateJin** [xinntao/BasicSR#376]
I use Anaconda to run ESRGAN. I just tried to import the head file in 'train.py' . Then I run the 'get_env_info()' function. It reports that there is no module named 'basicsr.version' . Just like the picture below.
How can I solve this problem? What things I need to provide? Or is there anything I can do ? Thanks you!
![image](https://user-images.githubusercontent.com/56467837/113759460-ad3f2180-9747-11eb-82f6-967351e58802.png)

**Comment by MLDrago** [comment]
Hello the error is not that important.
I modified the file as follow:
![github](https://user-images.githubusercontent.com/81963201/114602727-3a79fd00-9c97-11eb-91fb-065975d4c76c.png)

**Comment by MLDrago** [comment]
Hello,
This error is not really important.
You can find the version here : _BasicSR-master/VERSION_

By changing the function  _get_env_info_ as follow : 
Don't forget to change the path.

![github](https://user-images.githubusercontent.com/81963201/114605208-1ff55300-9c9a-11eb-9474-66ed553ee42d.png)

**Comment by ChocolateJin** [comment]
> Hello,
> This error is not really important.
> You can find the version here : _BasicSR-master/VERSION_
> 
> By changing the function _get_env_info_ as follow :
> Don't forget to change the path.
> 
> ![github](https://user-images.githubusercontent.com/81963201/114605208-1ff55300-9c9a-11eb-9474-66ed553ee42d.png)

Thank you for your reply. I delete all and rerun setup.py again . Now the question has been solved . It seems that is my personal question. Thank you again for your kindness . Have a nice day!
