### ISSUE TITLE
About loss function

### ISSUE THREAD

**Issue by njuhang** [xinntao/BasicSR#379]
Hello, what does TVLoss mean? It doesn't seem to be found in the article. Then is the loss of generator the sum of perceived loss, Gan loss and MSE loss?
你好，TVloss 是什么意思呢？在文章中好像没有发现。然后生成器的损失是感知损失＋GAN损失＋MSE损失三项的和吗？

**Comment by wwhio** [comment]
hello, TVLoss is total variation loss .
