### ISSUE TITLE
Error on training ESRGAN

### ISSUE THREAD

**Issue by themousepotato** [xinntao/BasicSR#380]
Hi, I encountered this error on training ESRGAN.

```
2021-04-16 03:02:39,923 INFO: Model [ESRGANModel] is created.
2021-04-16 03:02:39,992 INFO: Start training from epoch: 0, iter: 0
imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'

imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'

imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'

imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'

imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'

imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'

imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'

imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'

Traceback (most recent call last):
  File "basicsr/train.py", line 251, in <module>
    main()
  File "basicsr/train.py", line 197, in main
    train_data = prefetcher.next()
  File "/content/BasicSR/basicsr/data/prefetch_dataloader.py", line 76, in next
    return next(self.loader)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/BasicSR/basicsr/data/paired_image_dataset.py", line 83, in __getitem__
    img_gt = imfrombytes(img_bytes, float32=True)
  File "/content/BasicSR/basicsr/utils/img_util.py", line 122, in imfrombytes
    img = img.astype(np.float32) / 255.
AttributeError: 'NoneType' object has no attribute 'astype'

```

I couldn't find a workaround yet. Did anyone come across similar error? I'm using TIFF images for the training. They can be found at https://easy.dans.knaw.nl/ui/datasets/id/easy-dataset:158308/tab/2 - `RapidEye_5m` and `Sentinel-2_10m`.

**Comment by portizgit** [comment]
Hello, themousepotato, I'm trying to setup my environment for train with this model. 

I'm looking for the pretrained models of RRDB to train ESRGAN more quickly but I couldn't find it. How did you do the training? First train all de RRDB and them ESRGAN? 

If you know where I can get the pretrained model of RRDB i well very gratefull. 

When I try to train ESRGAN It shows me that error:

No such file or directory: 'experiments/051_RRDBNet_PSNR_x4_f64b23_DIV2K_1000k_B16G1_wandb/models/net_g_1000000.pth'

Thanks you

**Comment by jnjaby** [comment]
> Hi, I encountered this error on training ESRGAN.
> 
> ```
> 2021-04-16 03:02:39,923 INFO: Model [ESRGANModel] is created.
> 2021-04-16 03:02:39,992 INFO: Start training from epoch: 0, iter: 0
> imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'
> 
> imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'
> 
> imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'
> 
> imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'
> 
> imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'
> 
> imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'
> 
> imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'
> 
> imdecode_(''): can't read header: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/grfmt_tiff.cpp:148: error: (-215:Assertion failed) channels <= 4 in function 'normalizeChannelsNumber'
> 
> Traceback (most recent call last):
>   File "basicsr/train.py", line 251, in <module>
>     main()
>   File "basicsr/train.py", line 197, in main
>     train_data = prefetcher.next()
>   File "/content/BasicSR/basicsr/data/prefetch_dataloader.py", line 76, in next
>     return next(self.loader)
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 517, in __next__
>     data = self._next_data()
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
>     return self._process_data(data)
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
>     data.reraise()
>   File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 429, in reraise
>     raise self.exc_type(msg)
> AttributeError: Caught AttributeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/content/BasicSR/basicsr/data/paired_image_dataset.py", line 83, in __getitem__
>     img_gt = imfrombytes(img_bytes, float32=True)
>   File "/content/BasicSR/basicsr/utils/img_util.py", line 122, in imfrombytes
>     img = img.astype(np.float32) / 255.
> AttributeError: 'NoneType' object has no attribute 'astype'
> ```
> 
> I couldn't find a workaround yet. Did anyone come across similar error? I'm using TIFF images for the training. They can be found at https://easy.dans.knaw.nl/ui/datasets/id/easy-dataset:158308/tab/2 - `RapidEye_5m` and `Sentinel-2_10m`.

@themousepotato This may occur when `OpenCV` cannot load images. Check with your data path first and see if the code can correctly read `TIFF` images in `uint8` type.

**Comment by jnjaby** [comment]
> Hello, themousepotato, I'm trying to setup my environment for train with this model.
> 
> I'm looking for the pretrained models of RRDB to train ESRGAN more quickly but I couldn't find it. How did you do the training? First train all de RRDB and them ESRGAN?
> 
> If you know where I can get the pretrained model of RRDB i well very gratefull.
> 
> When I try to train ESRGAN It shows me that error:
> 
> No such file or directory: 'experiments/051_RRDBNet_PSNR_x4_f64b23_DIV2K_1000k_B16G1_wandb/models/net_g_1000000.pth'
> 
> Thanks you

You may need to carefully read the [ModelZoo.md](https://github.com/xinntao/BasicSR/blob/master/docs/ModelZoo.md) first. Download the pre-trained model you need by the download script. Hope this can help.

**Comment by portizgit** [comment]
Helo jnjaby, I have already download the pretrained models, but the RRDBNET_PSNR_x4.. pretrained_model it isn't on the google drive folder. 
If anyone had the pre-trained model on their computer. And he could upload it somewhere to be able to download it I would appreciate it. The training of the RRDB network, estimates me more than 1 month, that is why I need the pre-trained model to be able to train ESRGAN.

Thanks you

**Comment by jnjaby** [comment]
> Helo jnjaby, I have already download the pretrained models, but the RRDBNET_PSNR_x4.. pretrained_model it isn't on the google drive folder.
> If anyone had the pre-trained model on their computer. And he could upload it somewhere to be able to download it I would appreciate it. The training of the RRDB network, estimates me more than 1 month, that is why I need the pre-trained model to be able to train ESRGAN.
> 
> Thanks you

@portizgit it is renamed as `ESRGAN_PSNR_SRx4_DF2K_official-150ff491.pth` for publication. Just modify the path to the pre-trained model in `options/train/ESRGAN/train_ESRGAN_x4.yml`.
