### ISSUE TITLE
pre-trained model for EDVR

### ISSUE THREAD

**Issue by nounotabe** [xinntao/BasicSR#384]
Hi, thank you for sharing your exciting works!

Would you like to share the pre-trained model of EDVR trained on BD degradation?
(i.e. the model yielded 27.85dB on Vid4 in paper 'BasicVSR: The Search for Essential Components in Video Super-Resolution and Beyond')

thanks!

**Comment by xinntao** [comment]
You can ask Kelvin (kelvinckchan@outlook.com) for this pretrained model
