### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required. 

### ISSUE THREAD

**Issue by lc61900** [xinntao/BasicSR#386]
when I run the command "python setup.py develop"  with windows10  and pycharm Terminal.
something went wrong  "error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio"  "
I want to ask how can I run this project with windows os.
Thank you

**Comment by xinntao** [comment]
I have not tested it in windows. 
You may google it
