### ISSUE TITLE
Train ESRGAN with my own x3 data

### ISSUE THREAD

**Issue by ArthurT-Hub** [xinntao/BasicSR#389]
Hello!
I am training ESRGAN with my own x3 data. I modified train_ESRGAN_x4.yml, which includes the location of the training set and scale: 3, gt_size: 201.But  I encountered this error on training ESRGAN：
RuntimeError: The size of tensor a (268) must match the size of tensor b (201) at non-singleton dimension 3
Thank you！

**Comment by Samjith888** [comment]
Hey ,@ArthurT-Hub  . Did you trained the model  by using custom dataset  ?
