### ISSUE TITLE
There is an AttributeError in sr_model.py.

### ISSUE THREAD

**Issue by edgar2597** [xinntao/BasicSR#391]
When I tried to use ESRGAN, this problem appeared:

```
File "/content/BasicSR/basicsr/models/sr_model.py", line 121, in test
    if self.ema_decay > 0:
AttributeError: 'ESRGANModel' object has no attribute 'ema_decay'
```

I checked it and actually there is no attribute ema_decay for object ESRGANModel, thought it is used in line 121 in file sr_model.py.

**Comment by xinntao** [comment]
Hi @edgar2597 
Have you tried the latest codes?

basicsr1.3.1 may have this bug. But it should be fixed in the latest version

**Comment by ira7bar** [comment]
This is a bug introduced by the latest version.
self.ema_decay is defined only in init_training_settings(), so when running test it is not defined and thus not found.

**Comment by xinntao** [comment]
@ira7bar You are right! Thanks for pointing it out~ 
I will fix it now

**Comment by xinntao** [comment]
It has been fixed. 

It should be OK now. So I close it. 
If you still have problem, please reopen it~
