### ISSUE TITLE
NameError: name 'deform_conv_ext' is not defined

### ISSUE THREAD

**Issue by cvygkhv** [xinntao/BasicSR#392]
hi there and thanks for your amazing work.
When trying  to  reimplement EDVR,I ran into the  following obstacle and really need your help.

I run this line   `python train.py -opt=train\EDVR\train_EDVR_M_x4_SR_REDS.yml`   in CMD window,it shows :
` deform_conv_ext.modulated_deform_conv_forward(input, weight, bias, ctx._bufs[0], offset, mask, output,
NameError: name 'deform_conv_ext' is not defined`
![image](https://user-images.githubusercontent.com/84504402/118963803-6aed3f00-b999-11eb-884a-f0a2dc5a3888.png)

Looking forward to your reply!

**Comment by xinntao** [comment]
If you want to use compiled deformable conv, there are two ways:
1. Compile extensions when installation: git clone repo and run `python setup.py develop --cuda_ext` 
2. Compile it just-in-time: Add `BASICSR_JIT=True` before your cmd.

**Comment by cvygkhv** [comment]
@xinntao sorry to bother you again
 I choose the first way `python setup.py develop --cuda_ext`and it sucessfully finished in Git Bash.
But afterwards, when I try to run`python train.py -opt=train\EDVR\train_EDVR_M_x4_SR_REDS.yml`,the outcome is exactly the same as before,that is
![image](https://user-images.githubusercontent.com/84504402/118987639-0939ce80-b9b3-11eb-8b2f-67e65831f259.png)

**Comment by xinntao** [comment]
After executing `python setup.py develop --cuda_ext`, there should be some files (.so) in `ops/dcn` folder. You may check whether there are those files.

**Comment by xinntao** [comment]
BTW, it seems that you are running basicsr in windows, I am not sure whether it is OK in windows.

**Comment by cvygkhv** [comment]
there is a `dcn` folder
it is a windows

**Comment by xinntao** [comment]
In Ubuntu, there is a file named `deform_conv_ext.cpython-38-x86_64-linux-gnu.so` in the dcn folder. 
I do not know what will happens in Windows and you may google it.

**Comment by cvygkhv** [comment]
There is  a`deform_conv_ext.cp37-win_amd64.pyd`.
and thanks again

**Comment by xinntao** [comment]
Emmm, I am not sure what is the reason. Please google it~

**Comment by cvygkhv** [comment]
Ok ,thanks a lot

**Comment by Arrokoth0320** [comment]
maybe you should add the env vars “BASICSR_EXT=True”, and then setup the build
