### ISSUE TITLE
SRModel object has no attribute 'ema_decay'

### ISSUE THREAD

**Issue by zhaoyunpeng57** [xinntao/BasicSR#394]
Can someone tell me how to solve this problem?  Thank you.

**Comment by xinntao** [comment]
@zhaoyunpeng57 
Try the latest code v1.3.3
If you still have this problem, please let me know.

**Comment by zhaoyunpeng57** [comment]
I tried the latest code v1.3.3, but I still have this problem.. Could you please help me again? Thank you very much!
![image](https://user-images.githubusercontent.com/76091274/119296788-370d6480-bc8c-11eb-9efc-a352efabc908.png)

**Comment by xinntao** [comment]
It seems that your version is not 1.3.3. 

The Line 121 in sr_model.py should be: 
https://github.com/xinntao/BasicSR/blob/58d56ed14a73d5c27edb42f13bebd14082ea808d/basicsr/models/sr_model.py#L120-L124

**Comment by xinntao** [comment]
@zhaoyunpeng57 If you have solved this problem, I will close this issue. 
Please re-open it , if you still have this problem. Thanks.
