### ISSUE TITLE
'SRModel' object has no attribute 'net_g_ema'

### ISSUE THREAD

**Issue by shuodie** [xinntao/BasicSR#396]
I'm sorry that there is a low-level problem, but I don't know how to solve it, can you help me

**Comment by shuodie** [comment]
I cannot save the model

**Comment by Dae12-Han** [comment]
I also have  a same problem... In my case, I got 
'''
AttributeError: 'ESRGANModel' object has no attribute 'net_g_ema'
'''

**Comment by xinntao** [comment]
@shuodie @Dae12-Han 
Thanks for reporting this issue. 
1. Could you please check the BasicSR version. It should be fixed in the 1.3.3 version.
2. If you still have the problem, could you paste more logs?

**Comment by shuodie** [comment]
I used the 1.3.3 version,and i used my trian date and val data,but the following error still occurs.
Traceback (most recent call last):
  File "basicsr/train.py", line 221, in <module>
    train_pipeline(root_path)
  File "basicsr/train.py", line 212, in train_pipeline
    model.save(epoch=-1, current_iter=-1)  # -1 stands for the latest
  File "D:\anaconda3\lib\site-packages\basicsr\models\sr_model.py", line 206, in save
    self.save_network([self.net_g, self.net_g_ema], 'net_g', current_iter, param_key=['params', 'pa
rams_ema'])
AttributeError: 'SRModel' object has no attribute 'net_g_ema'

**Comment by xinntao** [comment]
@shuodie Thanks!

It is a bug and should be fixed now. 
you can use the latest master branch. Thanks. 

If you still have a problem, please let me know.
If the problem has been solved, please help close this issue. :-)

**Comment by shuodie** [comment]
i still have the porblem, is it because I use windows？

**Comment by xinntao** [comment]
I have tested on my laptop, it is OK now. You may check whether it is the latest version.

Otherwise, you can add this line to the option file
![image](https://user-images.githubusercontent.com/17445847/119458715-9ee8ab80-bd6f-11eb-9144-f427c60f5011.png)

**Comment by shuodie** [comment]
oh,god. Thank you. It's ok now!!!!!!!!!!
