### ISSUE TITLE
"No object named 'VideoTestVimeo90KDataset' found in 'dataset' registry!"

### ISSUE THREAD

**Issue by JoshonSmith** [xinntao/BasicSR#397]
Traceback (most recent call last):
  File "basicsr/test.py", line 46, in <module>
    test_pipeline(root_path)
  File "basicsr/test.py", line 29, in test_pipeline
    test_set = build_dataset(dataset_opt)
  File "/home/xxx/code/code2105/BasicSR/basicsr/data/__init__.py", line 34, in build_dataset
    dataset = DATASET_REGISTRY.get(dataset_opt['type'])(dataset_opt)
  File "/home/xxx/code/code2105/BasicSR/basicsr/utils/registry.py", line 65, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'VideoTestVimeo90KDataset' found in 'dataset' registry!"

**Comment by JoshonSmith** [comment]
version：1.3.3

**Comment by xinntao** [comment]
@JoshonSmith 
Thanks for reporting the bug.

I have a quick, please check whether it has been solved. (Please use the latest master branch)

If the problem has been solved, please help to close this issue.
If you still have a problem, please let me know. Thanks : )

**Comment by JoshonSmith** [comment]
Thanks !
It has been solved

**Comment by ds-giao** [comment]
@xinntao Hello, I have also encountered this issue in other projects. How did you solve it? thanks
