### ISSUE TITLE
test_mode bug

### ISSUE THREAD

**Issue by ALottoLearn** [xinntao/BasicSR#4]
I want to test the SR and SRGAN model. Now, I find a question :
Traceback (most recent call last):
  File "test.py", line 49, in <module>
    for data in test_loader:
  …
  …
  File "/opt/BasicSR-master/codes/data/util.py", line 262, in calculate_weights_indices
    if not math.isclose(weights_zero_tmp[0], 0.0, rel_tol=1e-6):
TypeError: a float is required

I tried to tranform the weights_zero_tmp[0] to floattensor, but it still don't work.

weights_zero_tmp_1 = torch.sum((weights == 0), 0)
    print(type(weights_zero_tmp_1))                                     #torch.ByteTensor
    weights_zero_tmp = weights_zero_tmp_1.float()
    print(type(weights_zero_tmp))                                       _**torch.FloatTensor**_
    print(type(weights_zero_tmp[0]))                                   _**torch.FloatTensor**_
    print(weights_zero_tmp[0])           #120 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 120[torch.FloatTensor of size 18]#
    if not math.isclose(weights_zero_tmp[0], 0.0, rel_tol=1e-6):
        indices = indices.narrow(1, 1, P - 2)
        weights = weights.narrow(1, 1, P - 2)
    if not math.isclose(weights_zero_tmp[-1], 0.0, rel_tol=1e-6):
        indices = indices.narrow(1, 0, P - 2)
        weights = weights.narrow(1, 0, P - 2)

**Comment by xinntao** [comment]
Sorry for the late reply.

I do not encounter this problem.
In the code, the corresponding line is 
if not math.isclose(weights_zero_tmp[0], 0, rel_tol=1e-6): # maybe you should change 0.0 to 0
And I print the type of weights_zero_tmp[0], it is torch.LongTensor. There is no float tensor. 

Hope it can help. 

If you still have the problem, you can first generate LR images using matlab temporarily.
