### ISSUE TITLE
NameError: name 'deform_conv_ext' is not defined (training EDVR)

### ISSUE THREAD

**Issue by candygogogogo** [xinntao/BasicSR#416]
/basicsr/ops/dcn/deform_conv.py
error in line 144
This file is always wrong, what should I do

**Comment by candygogogogo** [comment]
[](url)

**Comment by candygogogogo** [comment]
[F:\errorrr.png](url)

**Comment by candygogogogo** [comment]
![errorrr](https://user-images.githubusercontent.com/73946885/125717107-550127f9-a736-40f0-8b60-7b5209fb8deb.png)

**Comment by xinntao** [comment]
It is because the dcn compilcation fails.

1. uninstall basicsr. 
2. git clone basicsr repo.
3. python setup.py develop    to see whether the compilation is successful or not

**Comment by candygogogogo** [comment]
> It is because the dcn compilcation fails.
> 
> 1. uninstall basicsr.
> 2. git clone basicsr repo.
> 3. python setup.py develop    to see whether the compilation is successful or not

The Git Clone BasicSR can be compiled successfully from the very beginning, but I still have the same problem after the Git Clone BasicSR is compiled successfully according to what you said. I don't know what went wrong,

**Comment by xinntao** [comment]
Do you have the screen shot or log of the compilation?

Have you checked whether the compilation results are OK?

**Comment by candygogogogo** [comment]
![1](https://user-images.githubusercontent.com/73946885/125731577-b3fc913a-eed6-4128-b32b-432789e5f5db.png)
![2](https://user-images.githubusercontent.com/73946885/125731593-6d2c23a5-2f82-4e65-9ed2-42a8616523a5.png)
![3](https://user-images.githubusercontent.com/73946885/125731608-cdb958d8-fc6b-4653-9ed8-758a86cbe4e9.png)
![3 5](https://user-images.githubusercontent.com/73946885/125731625-327c00a4-70db-4b21-ae67-98d05d250614.png)
![4](https://user-images.githubusercontent.com/73946885/125731638-1d621bf2-2351-45ad-a592-598c8d2e671c.png)

**Comment by candygogogogo** [comment]
> Do you have the screen shot or log of the compilation?
> 
> Have you checked whether the compilation results are OK?

I have uploaded the screenshot for you to have a look

**Comment by xinntao** [comment]
You need to add env variable `BASICSR_EXT=True`:
`BASICSR_EXT=True python setup.py develop`

**Comment by candygogogogo** [comment]
I'm very sorry to waste so much of your time because of my own reasons, I'm really sorry.In addition, thank you very much for your reply to solve my problem. RESPECT!!!!!!!!!!!!!!!!!!!!!!!!
