### ISSUE TITLE
I want to build an SR structure myself, but No object named 'R2' found in 'arch' registry!"

### ISSUE THREAD

**Issue by shuodie** [xinntao/BasicSR#419]
I imitated the one written by   rrdbnet_arch.py

**Comment by beiyu555** [comment]
请问你解决了吗

**Comment by beiyu555** [comment]
请问你解决了吗

**Comment by beiyu555** [comment]
怎么解决的

**Comment by xinntao** [comment]
1.文件名后缀要是  `_arch.py`
2. 加入 @ARCH_REGISTRY.register()

**Comment by shuodie** [comment]
> 1.文件名后缀要是 `_arch.py`
> 2. 加入 @ARCH_REGISTRY.register()

谢谢您，这个问题在之前已经得到解决。还有一个小问题就是为什么RCAN的test的代码（test_RCAN.yml）和别的例如ESRGAN的test代码（ESRGAN\test_RRDBNet_PSNR_x4.yml）不一样，少了val：模块的代码无法运行，即使我按照其他test的yml文件加上val：，跑出来的测试集的PSNR远远低于训练的PSNR，我不知道问题出在哪里。
