### ISSUE TITLE
Missing keys in state_dict

### ISSUE THREAD

**Issue by NadaKingston** [xinntao/BasicSR#42]
I get the below issue while training  with both PSNR and ESRGAN pre-trained models.

   ```
     RuntimeError: Error(s) in loading state_dict for RRDBNet:
	Missing key(s) in state_dict: "model.1.sub.16.bias", "model.1.sub.16.weight".
``` 

Is it because the pre-trained model is now not compatible with RRDBNet model?

**Comment by xinntao** [comment]
Hi @NadaKingston ,

I have tried it but it is OK .

The keys in pretrained model are like "model.1.sub.16.RDB1.conv1.0.weight", "model.1.sub.16.RDB1.conv1.0.bias", etc.

You may check the configurations and the keys in constructed models.

**Comment by xhuvom** [comment]
@NadaKingston  have you solved it? I am facing the dame problem during training. My pre-trained model_G is `SRGAN_bicx4_303_505.pth` and `"which_model_G": "RRDB_net"`

**Comment by DanielWeMs** [comment]
This happens (at least in my case) if you change the scale value to something other than 4. I am still in the process of figuring out how to scale only by double instead of 4x.

**Comment by xinntao** [comment]
@DanielWeMs 
When dealing with another scale factor, you also need to use a different model.

**Comment by DanielWeMs** [comment]
Would it be possible to add support for x2 scale? I'm having a hard time getting this to work for that config. I am still very new to ML models, unfortunately.

**Comment by xinntao** [comment]
@DanielWeMs 
Sorry that we have not trained an ESRGAN model for x2 scale, you may train it by yourself.

**Comment by Feiyu-Zhang** [comment]
> Would it be possible to add support for x2 scale? I'm having a hard time getting this to work for that config. I am still very new to ML models, unfortunately.

You can comment pre-trained model in option/train/train_ESRGAN.
