### ISSUE TITLE
how to install to local env

### ISSUE THREAD

**Issue by btwbtm** [xinntao/BasicSR#423]
Hi, when I run BASICSR_EXT=True python setup.py develop, I always got a permission denied error. This is because I am using a shared environment. For example, when I use pip, I need to add --user. Is there a similar option or what modification should I make to install the package to local env?

**Comment by xinntao** [comment]
try `BASICSR_EXT=True python setup.py develop --user`

Ref: https://stackoverflow.com/questions/22551461/how-to-avoid-permission-denied-while-installing-package-for-python-without-sudo

**Comment by btwbtm** [comment]
Solved. Thx, xintao!
