### ISSUE TITLE
CUDA out of memory.

### ISSUE THREAD

**Issue by tongchangD** [xinntao/BasicSR#425]
This error occurred when I was testing the project
How to solve this error

Testing [DIV2K]...
Traceback (most recent call last):
  File "/media/tcd/data/work/Shanghai_Archives_Bureau/real_sr/codes/test.py", line 59, in <module>
    model.test()
  File "/media/tcd/data/work/Shanghai_Archives_Bureau/real_sr/codes/models/SRGAN_model.py", line 204, in test
    self.fake_H = self.netG(self.var_L)
  File "/media/tcd/software/anaconda3/envs/Archives_Bureau/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/tcd/software/anaconda3/envs/Archives_Bureau/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/media/tcd/software/anaconda3/envs/Archives_Bureau/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/tcd/data/work/Shanghai_Archives_Bureau/real_sr/codes/models/modules/RRDBNet_arch.py", line 69, in forward
    fea = self.lrelu(self.upconv2(F.interpolate(fea, scale_factor=2, mode='nearest')))
  File "/media/tcd/software/anaconda3/envs/Archives_Bureau/lib/python3.7/site-packages/torch/nn/functional.py", line 3132, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: CUDA out of memory. Tried to allocate 3.97 GiB (GPU 0; 7.79 GiB total capacity; 2.31 GiB already allocated; 4.00 GiB free; 2.56 GiB reserved in total by PyTorch)

**Comment by xinntao** [comment]
The network consumes too many GPU memories. 

If your input images are large, you may need to split the images into several sub-images, and then stitch after testing.

**Comment by tongchangD** [comment]
thanks, you are right.
To ensure that other partners do not have this problem
You can add the following code to your project.

`def cut_big_pic(img_path, source_min_img_path):
    img = cv2.imdecode(np.fromfile(img_path, dtype=np.uint8), -1)
    height, width, depth = img.shape
    height_cut = height // 256
    width_cut = width // 256
    pattern_height = 256
    pattern_width = 256
    for j in range(height_cut):
        for i in range(width_cut):
            #  切割的时候如果是靠边的最后一个就将图片加宽，保持原本的尺寸
            left_h = j * pattern_height
            left_w = i * pattern_width
            right_h = left_h + pattern_height
            right_w = left_w + pattern_width
            if i == width_cut - 1 or j == height_cut - 1:
                if i == width_cut - 1:
                    right_w = width if width >= width_cut * 256 else (left_w + pattern_width)
                if j == height_cut - 1:
                    right_h = height if height >= height_cut * 256 else (left_h + pattern_height)
            sub_img = img[left_h: right_h, left_w: right_w]
            cv2.imencode('.jpg', sub_img)[1].tofile(
                os.path.join(source_min_img_path, os.path.split(img_path)[1][:-4] + '_{}{}'.format(j, i) + '.jpg'))


def image_compose2(source_img_path, source_min_img_path, res_pic_path):
    # 获取 文件夹 中 的图片 数量及其 尺寸
    min_pic_file = os.listdir(source_min_img_path)
    img1 = cv2.imdecode(np.fromfile(os.path.join(source_min_img_path, min_pic_file[0]), dtype=np.uint8), -1)
    min_height, min_width, depth = img1.shape
    diff_width = 0
    diff_height = 0
    height_cut = 0
    width_cut = 0
    for file in min_pic_file:
        img1 = cv2.imdecode(np.fromfile(os.path.join(source_min_img_path, file), dtype=np.uint8), -1)
        height, width, depth = img1.shape
        if height != min_height:
            diff_height = height
        if width != min_width:
            diff_width = width
        nums = file[:-4].split("_")[1]
        if int(nums[0]) >= height_cut:
            height_cut = int(nums[0])
        if int(nums[1]) >= width_cut:
            width_cut = int(nums[1])
    height_cut += 1
    width_cut += 1

    diff_width = min_width if diff_width == 0 else diff_width
    diff_height = min_height if diff_height == 0 else diff_height

    print(diff_width, diff_height)

    new_image = Image.new('RGB',
                          (min_width * (width_cut - 1) + diff_width, min_height * (height_cut - 1) + diff_height))

    for j in range(height_cut):
        for i in range(width_cut):
            print(os.path.join(source_min_img_path,
                               os.path.split(source_img_path)[1][:-4] + '_{}{}'.format(j, i) + '.png'))
            temp_images = Image.open(os.path.join(source_min_img_path,
                                                  os.path.split(source_img_path)[1][:-4] + '_{}{}'.format(j,
                                                                                                          i) + '.png'))
            new_image.paste(temp_images, (i * min_width, j * min_height))
    return new_image.save(res_pic_path)
`

**Comment by xinntao** [comment]
@tongchangD Thanks,

You can also find an alternative  in RealESRGAN repo: https://github.com/xinntao/Real-ESRGAN
(in the inference_realesrgan.py file, `tile` option)

Sorry for the late notice, as I just updated it yesterday~

**Comment by tongchangD** [comment]
hhh,thanks
