### ISSUE TITLE
Blue rectangles on faces

### ISSUE THREAD

**Issue by smituk** [xinntao/BasicSR#428]
### How can I fix blue rectangles on faces?

Log for the case on picture:

Processing 000609.png image ...
Detect several faces and only keep the largest.
	Detect 1 faces, 1 landmarks.
Cannot find faces in cropped image with index 0.
	Detect 0 faces for 68 landmarks.
	Face restoration ...
Landmarks is None, skip cropped faces with idx 0.
	Generate the final result ...

I tried only_keep_largest=True

https://github.com/xinntao/BasicSR/blob/cf1e32cdfc9710041ed497e9f5c155ceb7567c8f/basicsr/utils/face_util.py#L68

But it happen any way.

Is it possible to process faces started from 70x70px and more? not 1 larger, but all larger specific size?

Thanks
<img width="161" alt="faces_err" src="https://user-images.githubusercontent.com/1440776/128638243-ec427c0b-46cd-40f8-90c0-a53a8a0327a7.png">

**Comment by xinntao** [comment]
The color channel may be incorrect. 

Recommended to try our new face restoration model: [GFPGAN](https://github.com/TencentARC/GFPGAN)
