### ISSUE TITLE
Do I need to modify the model to support scale x3 not x4? 

### ISSUE THREAD

**Issue by Jing25** [xinntao/BasicSR#43]
Hi,

If I need scale x3 not x4, should I modify the model and train it from scratch? Where do I need to modify..?

Thank you

**Comment by xinntao** [comment]
Hi @Jing25 ,
I think you should check the followings:
1) check the data preparation;
2) check the network structure, For SRResNet/RRDBNet class, you could pass the paramteter `upscale=3`;
3) check the configuration json file: e.g.,  `scale`

You can train from cratch, or use the pre-trained X4 network as initialization. For the latter, you may need to write a script to extract the parameters of X4 model and assign to the X3 model.

**Comment by zzoon91** [comment]
I guess the classifier in Discriminator should be changed, too.
If you don't, you'll get a size mismatch error.

**Comment by Jing25** [comment]
How to extract the parameters of x4 to x3..?

**Comment by xinntao** [comment]
Hi @Jing25 
You can extract parameters of conv layers in X4 model and use them in the X3 model. And only initialize the upsampling layers in the X3 model.

**Comment by Jing25** [comment]
It works. Thanks!

**Comment by DanielWeMs** [comment]
@Jing25 Would it be possible for you to share the changes you made to make this work? Thanks!

**Comment by Jing25** [comment]
@DanielWeMs I add code in, for example, SR_model.py as below:

        if opt['scale'] == 4 or self.is_train == False:
            self.netG = networks.define_G(opt).to(self.device)
            self.load()

        else:  # x3
            # load pretrained models e.g. x4 model
            load_path_G = self.opt['path']['pretrain_model_G']
            pretrained_dict = torch.load(load_path_G)

        # 1. filter out unnecessary keys
            pretrained_dict = {'module.' + k: v for k, v in pretrained_dict.items() if k.startswith('model.0.') or k.startswith('model.1.')}

            # define network and load pretrained models
            self.netG = networks.define_G(opt).to(self.device)
            model_dict = self.netG.state_dict()

        # 2. overwrite entries in the existing state dict
            model_dict.update(pretrained_dict)

        # 3. load the new state dict
            self.netG.load_state_dict(model_dict)

**Comment by wl082013** [comment]
> It works. Thanks!

@Jing25 How did you make it work ?  for x3, do we need to change GT size from 128 to something else? 
since 128/3 is not an integer, it could not be used for ESRGAN training!
Thanks a lot

**Comment by Jing25** [comment]
@wl082013 Yes, 128 is not applicable for x3. I use 96 instead. The good thing is, the discriminator for image size 96 have been included in their code base. You can easily change the discriminator in the option file.
