### ISSUE TITLE
Issue with simple testing

### ISSUE THREAD

**Issue by gigan12** [xinntao/BasicSR#45]
I'm just getting into it and already got a problem with testing the pre-trained Esrgan model.

When running it I get the following error message which seems to be a windows related Pytorch issue:
  
    File "C:\Users\Steven\Anaconda3\lib\multiprocessing\spawn.py", line 136, in 
    _check_not_importing_main
    is not going to be frozen to produce an executable.''')
      RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Any idea how to fix it?

**Comment by Ifinxx** [comment]
I'm running on windows and get the same error. Did you resolve this by editing spawn.py?

**Comment by gigan12** [comment]
I moved completely to my Linux Distribution which I need for my studies anyway. There are more possible errors with Windows due to Pytorch, I didn't want to spend much time on fixing everything. Works flawlessly there.
