### ISSUE TITLE
涛哥，有几个问题请教一下

### ISSUE THREAD

**Issue by zkh123456789** [xinntao/BasicSR#455]
涛哥，我在训练ESRGAN的生成器RRDBNet时候有几个问题想向您请教一下：
1.我在训练4倍RRDBNet之前可不可以先训练1个2倍的RRDBNet模型作为4倍的预训练模型？
2.RRDBNet里面有几个参数 我不是很明白是啥意思，想问您一下：
（1）num_worker_per_gpu: 6  这个num_worker_per_gpu 代表啥？
（2）num_grow_ch: 32  这个num_grow_ch代表啥？
麻烦涛哥帮忙解答下~~~~

**Comment by zkh123456789** [comment]
@xinntao

**Comment by xinntao** [comment]
1. 是可以的，我一般先训练x4的
2. 1） 每个gpu 的dataloader进程数; 2) 你可以看RRDBNet的arch，直接看代码就知道了

**Comment by zkh123456789** [comment]
> 1. 是可以的，我一般先训练x4的
> 2. 1） 每个gpu 的dataloader进程数; 2) 你可以看RRDBNet的arch，直接看代码就知道了

 感谢涛哥的解答！
