### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by AK391** [xinntao/BasicSR#457]
Collecting basicsr
  Downloading basicsr-1.3.3.10.tar.gz (131 kB)
[91m    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yoi3y9k3/basicsr_9e261316900345abbad7c5318e334cb4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yoi3y9k3/basicsr_9e261316900345abbad7c5318e334cb4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1qwtrpko
         cwd: /tmp/pip-install-yoi3y9k3/basicsr_9e261316900345abbad7c5318e334cb4/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yoi3y9k3/basicsr_9e261316900345abbad7c5318e334cb4/setup.py", line 8, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------

**Comment by AK391** [comment]
resolved

**Comment by kunalchamoli** [comment]
@AK391 how did the your issue resolved ?

**Comment by fabiom91** [comment]
Resolved how? I have the same issue :(

**Comment by joaquinmenendez** [comment]
any update about this error?

**Comment by mv-lab** [comment]
same problem for version 1.3.5

**Comment by angelicaba23** [comment]
same problem for version 1.3.5

**Comment by desyang-hub** [comment]
Maybe it's an issue with the setuptools version, on basicsr==1.2.0 I replaced setuptools==78.1.1 and installed successfully
