### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by PASSENGER128** [xinntao/BasicSR#460]
在我的实验中引用了您提出的RRDB block，但是训练结果中PSNR超过了当前的最高水平，但是SSIM指标低于最高水平（当前ssim指标达到了0.931，但是我的才0.861），损失函数使用的是10(1-ssim)+L1。请问您遇到过这种情况吗？碰到这种情况您对于我继续做实验有什么建议吗？谢谢您的回复。

**Comment by PASSENGER128** [comment]
还有一个问题，您在训练您的RRDB net时碰到过网络难以训练的问题吗？在使用您的RRDBnet时，在靠近输入的地方梯度会达到1e-5，疑似发生梯度消失。（但是残差和密集链接不是在一定程度上缓解了梯度消失吗?）。期待您的指教。

**Comment by xinntao** [comment]
1. 一般PSNR和SSIM呈现正相关的， 如果差距很大的化，可以看下是否使用了同样的SSIM计算代码。
2. 过深的网络可能会导致较小的梯度，你可以加一些connection来看是否有改善， 个人感觉这个梯度还是有效的。
