### ISSUE TITLE
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### ISSUE THREAD

**Issue by Musclemanisme** [xinntao/BasicSR#461]
![bug](https://user-images.githubusercontent.com/38111433/130596443-7c144513-fd28-4d30-8219-b53a174d4b46.png)

您好，我在使用dcn的过程中出现了图中的错误，只要batch size大于等于2就报错；我检查了我的代码并没有使用view()这个方法，只有在dataloader之前使用了albumentations里面的ToTensorV2，那个里面对ndarray进行了transpose操作，不知道您有没有碰到过这个问题？
感谢！

**Comment by xinntao** [comment]
我没有在dcn中关于过这个问题，
我觉得可以：
1. 检查是否有对dcn有误修改
2. 如果没有的话，可以对输入到dcn前的tensor先clone一下，看看是否可以解决。若是，可能是不连续，查看具体原因， 若必要，可以调用contiguous()

**Comment by wwhio** [comment]
我有遇到过相似的问题。可以尝试使用 mmcv-full 或者 torchvision 中的  deformable convolution 替代。

**Comment by xinntao** [comment]
原来torchvision中已经有deformable conv了， 谢谢提供这个信息，
后面看看能否把 basicsr里面的dcn替换成torchvision中的deformable convolution

**Comment by xinntao** [comment]
> .contiguous()

原来的ops 引起的问题， 只要 添加一个 .contiguous() 应该就可以解决了吧？

**Comment by xinntao** [comment]
> 我有遇到过相似的问题。可以尝试使用 mmcv-full 或者 torchvision 中的 deformable convolution 替代。
> 
> 问题复现代码：
> 
> ```
> import torch
> from basicsr.ops.dcn import DeformConvPack
> 
> class TestModule(torch.nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.dcn = DeformConvPack(3, 3, 3, 1, 1)
>     
>     def forward(self, x):
>         # assume channel of x is [n, t, c, h, w]
>         # output is [n*t, c, h, w]
>         n, t, c, h, w = x.shape
>         x0 = x.reshape(-1, c, h, w)
> #         x0 = x.view(-1, c, h, w).contiguous()
> #         x0 = x0.clone()
>         x1 = self.dcn(x0)
>         return x1
> 
> test = TestModule().cuda()
> a = torch.randn(2, 5, 3, 16, 16, device='cuda')
> a_hat = test(a)
> a_loss = torch.sum((a_hat - torch.randn(a_hat.shape, device=a_hat.device))**2)/a_hat.numel()
> a_loss.backward()
> ```

原来的ops 引起的问题， 只要 添加一个 .contiguous() 应该就可以解决了吧？

**Comment by wwhio** [comment]
> 添加一个 .contiguous()

并不能。

**Comment by Musclemanisme** [comment]
> > 我有遇到过相似的问题。可以尝试使用 mmcv-full 或者 torchvision 中的 deformable convolution 替代。
> > 问题复现代码：
> > ```
> > import torch
> > from basicsr.ops.dcn import DeformConvPack
> > 
> > class TestModule(torch.nn.Module):
> >     def __init__(self):
> >         super().__init__()
> >         self.dcn = DeformConvPack(3, 3, 3, 1, 1)
> >     
> >     def forward(self, x):
> >         # assume channel of x is [n, t, c, h, w]
> >         # output is [n*t, c, h, w]
> >         n, t, c, h, w = x.shape
> >         x0 = x.reshape(-1, c, h, w)
> > #         x0 = x.view(-1, c, h, w).contiguous()
> > #         x0 = x0.clone()
> >         x1 = self.dcn(x0)
> >         return x1
> > 
> > test = TestModule().cuda()
> > a = torch.randn(2, 5, 3, 16, 16, device='cuda')
> > a_hat = test(a)
> > a_loss = torch.sum((a_hat - torch.randn(a_hat.shape, device=a_hat.device))**2)/a_hat.numel()
> > a_loss.backward()
> > ```
> 
> 原来的ops 引起的问题， 只要 添加一个 .contiguous() 应该就可以解决了吧？

我有尝试对tensor加.contiguous()操作，但是不奏效

**Comment by Musclemanisme** [comment]
> 原来torchvision中已经有deformable conv了， 谢谢提供这个信息，
> 后面看看能否把 basicsr里面的dcn替换成torchvision中的deformable convolution

感谢，使用mmcv的DeformConv2dPack没有报错！

**Comment by xinntao** [comment]
@automatic0313 
添加了 使用 `torchvision.ops.deform_conv2d` 的支持， 它们的结果是一样的。供参考~

(Note that the torchvision version should be >=0.9.0, therefore pytorch version >=1.8.0)
https://github.com/xinntao/BasicSR/blob/1ca522852049f48504afaab9df588735abbcec9b/basicsr/archs/arch_util.py#L230-L235
