### ISSUE TITLE
The same number of images will create different .pkl files.

### ISSUE THREAD

**Issue by 493762436** [xinntao/BasicSR#462]
Hi,xintao! Thanks for your great work first!
I want to train EDVR by using my own datasets including 80000 images. But when I use create_lmdb.py to create train_sharp.lmdb and train_sharp_bicubic.lmdb, I find that the meta_info.pkl is different like 2.1MB and 2.3MB. I'm sure that the subfolder and images of the LR and HR images are same, and it will be OK when I try other datasets including less images like 20000.
Did you ever encounter the same case? Hope for your reply, thanks!

**Comment by xinntao** [comment]
Hi @493762436 
It seems that you are using the old version of BasicSR (from `meta_info.pkl`). I am not sure whether it is OK, and you need to check whether they contain the same contents.

I strongly recommend you using the latest BasicSR, where the meta information is stored as `meta_info.txt`, which is more readable.

**Comment by 493762436** [comment]
> Hi @493762436
> It seems that you are using the old version of BasicSR (from `meta_info.pkl`). I am not sure whether it is OK, and you need to check whether they contain the same contents.
> 
> I strongly recommend you using the latest BasicSR, where the meta information is stored as `meta_info.txt`, which is more readable.

Thanks a lot ! And I have found that the names of LR and HR images are different (eg. 00.png & 00x4.png). As you said, I used the old version of BasicSR (from meta_info.pkl), and it seems that it should use the same naming.
