### ISSUE TITLE
about DataParallel（DP）with multi-gpus in testing

### ISSUE THREAD

**Issue by NothingToSay99** [xinntao/BasicSR#466]
Thanks for your great works!
And I have confused that Why it can be achieved with 2 GPUs in the training phase,  however in the testing phase, DataParallel is not working？ So that the test.py only works on one of 2 GPUs, the other one's memory is always zero. 
Add:  the param "num_gpu: 2" in the test.yml.
Looking forward to your answer! thanks so much.

**Comment by jnjaby** [comment]
Hi, this is because the batch size of dataloader is set to be 1 during the testing phase. See the following code https://github.com/xinntao/BasicSR/blob/3c30fb3661d8fdb4a05fbab793ce47312b09d802/basicsr/data/__init__.py#L78

**Comment by NothingToSay99** [comment]
@jnjaby yeah, u r right. Thanks for your reminding
