### ISSUE TITLE
Some doubt about calculating R1 loss/ PL loss in styleGAN2

### ISSUE THREAD

**Issue by BIGJUN777** [xinntao/BasicSR#470]
Hello, thank you for sharing your great work.

Do you have any idea on [this part](https://github.com/xinntao/BasicSR/blob/387b8b69e45d0ca0205f03a47792461a3ba52538/basicsr/models/stylegan2_model.py#L213) (about calculating corresponding regulation losses in styleGAN), where you left "TODO" mark in the past? I am also confused about this.

Thanks.

**Comment by xinntao** [comment]
I have no further updates. 
I conjecture it is because the `real_pred` is used in r1_penalty, but is not involved in the loss function.  So we need to use it in the loss.

**Comment by BIGJUN777** [comment]
Thank you for your reply.

Maybe you are right. When this kind of error arising, it suggested all outputs from "forward" phase should be involved in calculating loss.

**Comment by xinntao** [comment]
If there is no other update, I will close this issue. If you have any questions, please re-open it. Thanks 😄
