### ISSUE TITLE
训练维度错误。。。

### ISSUE THREAD

**Issue by zkh123456789** [xinntao/BasicSR#472]
涛哥好，最近训练RRDBNet时，我用4倍的可以直接训练，调整参数也不会报错；但是训练2倍和8倍的模型时，就报了维度错误。。。。。请问涛哥怎么解决这个问题。。。
![image](https://user-images.githubusercontent.com/55131043/134467738-711af63b-5e03-486e-904e-ca2bf8d18723.png)

**Comment by xinntao** [comment]
看起来是 维度的不同
检查
1. 数据shape是否dui
2. 更改后的网络维度是否能够正常forward。是否在这里出现了问题

**Comment by zkh123456789** [comment]
> 看起来是 维度的不同
> 检查
> 
> 1. 数据shape是否dui
> 2. 更改后的网络维度是否能够正常forward。是否在这里出现了问题

我再三检查了 hr和lr的维度，我的hr是256*256的，2倍lr是128*128，4倍是64*64，8倍是32*32， 我用您的原始的RRDBNet训练，还是出现了类似的情况，只有4倍的可以正常run，2倍和8倍都会报维度错误。。

**Comment by xinntao** [comment]
你应该修改了网络结构吧，只forward 网络结构，然后debug， print tensor shape，查看问题出在哪里

**Comment by zkh123456789** [comment]
> 你应该修改了网络结构吧，只forward 网络结构，然后debug， print tensor shape，查看问题出在哪里

 我换回了你原始的RRDBNet，也是这样--  我试试您说的方法把  感谢涛哥解答~

**Comment by xinntao** [comment]
如果没有其他问题，我先暂时close了， 如果还有问题， 可以再次open this issue~
