### ISSUE TITLE
用自己的数据集训练EDVR

### ISSUE THREAD

**Issue by Secant1998** [xinntao/BasicSR#483]
您好，非常感谢您作出这个实用的SR工具，现在我想用自己制作的视频数据集去训练EDVR，但是我的预设有些不太清楚的地方

**Comment by Secant1998** [comment]
meta_info里的内容我也相对应地改了的：

000 128 (1080,1920,3)
001 128 (1080,1920,3)
002 128 (1080,1920,3)
003 128 (1080,1920,3)
004 128 (1080,1920,3)
005 128 (1080,1920,3)
006 128 (1080,1920,3)
007 128 (1080,1920,3)
008 128 (1080,1920,3)
009 128 (1080,1920,3)
010 128 (1080,1920,3)
011 128 (1080,1920,3)
012 128 (1080,1920,3)
013 128 (1080,1920,3)
014 128 (1080,1920,3)
015 128 (1080,1920,3)
016 128 (1080,1920,3)

**Comment by Secant1998** [comment]
您好，我找出了问题，是最后多了一行空白导致读取错误
......
197 128 (1080,1920,3)
198 128 (1080,1920,3)
199 128 (1080,1920,3)
200 128 (1080,1920,3)
（这里有一行空白忘去掉了）

**Comment by Secant1998** [comment]
您好，虽然上一个问题解决了，但是我得预设好像还是有问题，请问一下如果我用自己的这个数据集进行训练的话，dataset的type我该如何选择

**Comment by IceClear** [comment]
You need to rewrite your dataloader for your own data. Generally, the definition of the dataloaders are [here](https://github.com/xinntao/BasicSR/tree/master/basicsr/data) and you need to write your dataloader in one file follow the pre-defined dataloaders. Then just change your .yml file to use your dataloader.
