### ISSUE TITLE
在按照BasicSR Examples开发时：ModuleNotFoundError: No module named 'basicsr.archs.example_arch'

### ISSUE THREAD

**Issue by successhaha** [xinntao/BasicSR#492]
xintao，你好。在按照BasicSR Examples开发时，遇到了这个错误，整个流程都是按照你的样例走下来的。想问下这个错误是什么原因？

**Comment by successhaha** [comment]
这个问题解决了，第一次用basicsr做开发，需要在conda环境中找到basicsr，然后进行修改。

**Comment by jjn123456** [comment]
请问可以细说一下在conda里面修改basicsr吗？
