### ISSUE TITLE
How to prepare train data for SFT-GAN?

### ISSUE THREAD

**Issue by zhanghuan18332552065** [xinntao/BasicSR#5]
I want to use DIV2K800 dataset to train SFT-GAN, but I don't know which folder should I  put DIV2K800 segmentation .pth files?  And does the  OutdoorScene testing dataset require my manual classification?

**Comment by xinntao** [comment]
Sorry for the late reply.
1. SFT-GAN now relies on segmentation and DIV2K may not be a proper dataset to do segmentation. 
2. The code is now for OutdoorScene dataset only. The dataset preparation is described in https://github.com/xinntao/BasicSR/tree/master/codes/data. If you want to use other datasets, you need to modify the data loader code, e.g., LRHR_seg_bg_dataset.py.
3. For OutdoorScene testing dataset, we use the same predefined classes as those in the training phase. First, run test_seg.py to get the segmentation .pth, and then run SFT-GAN to get the final results.

**Comment by zhanghuan18332552065** [comment]
Thanks for you reply, I can train it now.

**Comment by ackbar03** [comment]
@zhanghuan18332552065  did you manage to train your own dataset using sft-gan? From reading the code it seems to me that training can only be done using OST dataset since it needs to be pre-labeled. To train on own dataset it may require a different training procedure.

**Comment by xinntao** [comment]
Hi @ackbar03 ,
Now SFTGAN only supports OST dataset. 
The major limitation is the segmentation. It is a bit challenging to obtain accurate segmentation results for arbitrary natural images with arbitrary labels.

It also limits the use in practical scenarios. One possible research direction is to extract mid-level segmentation maps, like the super-pixel segmentation.

**Comment by anguoyang** [comment]
Hi @xinntao ,thank you for the contribution, as you said SFTGAN only supports OST dataset right now, so the following configuration is not correct right?:
  , "datasets": {
    "train": {
      "name": "OST"
      , "mode": "LRHRseg_bg"
      , "dataroot_HR": "/mnt/SSD/xtwang/BasicSR_datasets/OST/train/img"
      , "dataroot_HR_bg": "/mnt/SSD/xtwang/BasicSR_datasets/DIV2K800/DIV2K800_sub"
      , "dataroot_LR": null
      , "subset_file": null
      , "use_shuffle": true

I was puzzled on DIV2K800_sub and dataroot_HR_bg, I check the source code, it seems it read HR images from either dataroot_HR or dataroot_HR_bg randomly, but the bicseg(generated from OST) is just for dataroot_HR(OST), I  don't know what is it(dataroot_HR_bg) for .

BTW, I totally agree with you that in practical scenarios, there are so many priors needed, 8 classes is not enough but " difficult to obtain accurate segmentation results for arbitrary natural images with arbitrary labels."
my question is: what is "mid-level segmentation maps"? is there any papers on super-pixel segmentations? thank you.

**Comment by anguoyang** [comment]
I see, the dataroot_HR_bg is for background images with seg[...]=1, but still don't understand why we need this segmentation, to get more training data? but for div2k800, the image prior is just set to 1 without segmentation
