### ISSUE TITLE
SRGAN testing configuration

### ISSUE THREAD

**Issue by Holmes-Alan** [xinntao/BasicSR#51]
How to write configuration for SRGAN(Not ESRGAN) testing? I always encounter the "missing key in state_dict" problem.

**Comment by xinntao** [comment]
Hi @Holmes-Alan , 
1. Download the model [`SRGAN_bicx4_303_505.pth`](https://drive.google.com/drive/folders/1WR2X4_gwiQ9REb5fHfNnBfXOdeuDS8BA)
2. I have updated the file in options/test folder
