### ISSUE TITLE
AMD GPU Support / Training Questions

### ISSUE THREAD

**Issue by Ifinxx** [xinntao/BasicSR#52]
I have a couple of questions regarding the hardware required to train the AI. Is it possible to do this with CPU or AMD GPU's? In the future do you plan on making a GUI to simplify the training procedures?

**Comment by xinntao** [comment]
Hi @Ifinxx 

Lots of deep-learning based methods need GPU to accelerate training. Using CPU for training is too slow to tolerate. It is almost impossible to train large and deep models with CPU. 

We use Nvidia GPUs with CUDA. I have not tried other GPUs like AMD. I think it may need to figure out the settings to run with these GPUs. 

And there is no plan to add a GUI for this repo.

**Comment by Ifinxx** [comment]
I did some research and found this: https://github.com/ROCm-Developer-Tools/HIP
Maybe this is something that can be done in the future?

**Comment by xinntao** [comment]
@mixtresh 
Check if the bottleneck is the IO or cpu resources. `top/htop, iotop` may help.

**Comment by xinntao** [comment]
It may be blocked by the IO, you can check the IO.

**Comment by mixtresh** [comment]
![default](https://user-images.githubusercontent.com/37978776/51374040-cfbad500-1b12-11e9-8cde-09793977c056.png)
I/O on 1%

**Comment by xinntao** [comment]
So the bottleneck is the IO, 

Sorry that I do not know the solution of `n_workers` in windows.

**Comment by mirh** [comment]
Back to the first actual question...
AFAIU opencv transparent api should already be able to handle many/most functions through opencl. 
As for pytorch, there isn't an opencl backend, but there is an HIP one already: https://github.com/pytorch/pytorch/issues/10657#issuecomment-415067478
