### ISSUE TITLE
saving and loading from checkpoints not work

### ISSUE THREAD

**Issue by mixtresh** [xinntao/BasicSR#54]
```
Traceback (most recent call last):
  File "T:/BasicSR/codes/train.py", line 155, in <module>
    main()
  File "T:/BasicSR/codes/train.py", line 33, in main
    util.setup_logger(None, opt['path']['log'] + 'T:/train.log', level=logging.I
NFO, screen=True)
AttributeError: module 'utils.util' has no attribute 'setup_logger'
```

previous  "saving and loading from checkpoints" work fine but only if i add 
```
import logging
logger = logging.getLogger(__name__)
```
in train, but not save checkpoint model
i use conda on win 8.1

**Comment by xinntao** [comment]
Have just pulled a modified version of saving and loading training state. You may try it to see whether it is working.
It saves the training states separately while saving the models. When resuming training, just pass a option with the name `resume_state`, like , `"resume_state": "../experiments/debug_001_RRDB_PSNR_x4_DIV2K/training_state/200.state"`.
