### ISSUE TITLE
create_lmdb Will be killed inexplicably

### ISSUE THREAD

**Issue by JusperLee** [xinntao/BasicSR#57]
When I use create-lmdb, there is no problem reading data. When I write data, it will be killed inexplicably.

**Comment by xinntao** [comment]
Did you mean writing to lmdb files?
When writing to lmdb files, it consumes lots of memory. If it exceeds the maximum, it will crash. 
You can check it.

**Comment by zhLawliet** [comment]
@JusperLee How to solve this problem when the data is large？

**Comment by xinntao** [comment]
@JusperLee  You modify the creating lmdb codes to use less memory. Actually, you can read part of the data and then write it to lmdb

**Comment by SymphonyPy** [comment]
For me, I saved every img to .lmdb file immediately instead of saving it to list

**Comment by Cugtyt** [comment]
@SymphonyPy Did you solve it?

**Comment by Cugtyt** [comment]
@SymphonyPy Do you mean this?

``` python
with env.begin(write=True) as txn:  # txn is a Transaction object
    for i, v in enumerate(img_list):
        pbar.update('Write {}'.format(v))
        base_name = os.path.splitext(os.path.basename(v))[0]
        key = base_name.encode('ascii')
        data = cv2.imread(v, cv2.IMREAD_UNCHANGED) #dataset[i] <------- this is the change
        if data.ndim == 2:
            H, W = data.shape
            C = 1
        else:
            H, W, C = data.shape
        meta_key = (base_name + '.meta').encode('ascii')
        meta = '{:d}, {:d}, {:d}'.format(H, W, C)
        # The encode is only essential in Python 3
        txn.put(key, data)
        txn.put(meta_key, meta.encode('ascii'))
```
But still out of memory.
