### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by Dawsonpei** [xinntao/BasicSR#59]
Hi! I met a question about bus error using docker durring training. Someone online told me to modify num_workers to zero, but I do not know how to do this.

Here is the RuntimeError:
DataLoader worker (pid 20991) is killed by signal: Bus error. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

**Comment by mrsabhar** [comment]
Had same issue.. I did workaround by loading directly from images instead of lmdb. Issue maybe from software setup (based on searches).

**Comment by Dawsonpei** [comment]
The issue appeared when the model was saved at the end of iteration 5000. And I just fit the configuration in file "options/train/train_esrgen.json". Error occurred at Each time I operate to this point——validation.

**Comment by geyuxi** [comment]
I had same issue. @Dawsonpei Have you solved the problem？
