### ISSUE TITLE
I also want to ask where the epoch was set

### ISSUE THREAD

**Issue by JusperLee** [xinntao/BasicSR#66]

**Comment by JusperLee** [comment]
Training of the epoch

**Comment by JusperLee** [comment]
![image](https://user-images.githubusercontent.com/33806018/52124687-00e3eb00-2665-11e9-8cc7-bbdf53440e96.png)
![image](https://user-images.githubusercontent.com/33806018/52124747-3688d400-2665-11e9-8a17-fb0005a25147.png)
Is the content of the above niter and the following epoch the same?

**Comment by JusperLee** [comment]
@xinntao

**Comment by xinntao** [comment]
I prefer to use the **iteration** counter than **epoch** counter, so that when changing to another dataset with a different number of images, we can reuse the settings, like learning rate and learning rate scheme. 

The epoch can be calculated from n_inter and the number of image dataset.

**Comment by JusperLee** [comment]
Thank you very much
