### ISSUE TITLE
Filenames of LR and HR images

### ISSUE THREAD

**Issue by Faberman** [xinntao/BasicSR#71]
I've used `generate_mod_LR_bic.m` script to downsample HR images, but I've just noticed, that LR images have `_bicLRx4` suffix. Should I stop the training process and rename them to match HR images filenames? Or only file order in those two folders really matters?

**Comment by xinntao** [comment]
If you use BasicSR codes, it does not matter.
Only the image order matters.

**Comment by Faberman** [comment]
Got it, thanks. Yes, I use BasicSR codes.
