### ISSUE TITLE
How did you get the RRDB_ESRGAN_x4 model?

### ISSUE THREAD

**Issue by zhLawliet** [xinntao/BasicSR#72]
@xinntao  Can you describe your process in detail about the process for RRDB_ESRGAN_x4?
(1)I use the `RRDB_PSNR_x4.pth` model as the pre-trained model. 
(2)  the dataSet is DIV2K800. which is by your  	extract_subimgs_single.py and   	generate_mod_LR_bic.m create_lmdb.py 
(3) I donot change the configuration of  train_ESRGAN.json.  
When i test the Set14.
RRDB_ESRGAN_x4(your model)   PSNR: 24.495635 dB; SSIM: 0.654736  PSNR_Y: 26.283511 dB; SSIM_Y: 0.698408
RRDB_ESRGAN_x4(my model, which is :285000_G)   PSNR: 25.258169 dB; SSIM: 0.666064  PSNR_Y: 27.158507 dB; SSIM_Y: 0.725785

but my result looks very vague.

**Comment by xinntao** [comment]
@zhLawliet  
For RRDB_ESRGAN, it used more data to train. But I don't think it is the key point.  With more training, (like 400k or 500k), will the results look better?

Can you share your log and your results?

**Comment by zhLawliet** [comment]
OK
