### ISSUE TITLE
Weird artifacts with PSNR-oriented model 

### ISSUE THREAD

**Issue by oubathAI** [xinntao/BasicSR#73]
Hi @xinntao 

Thanks for your repo; your paper on ESRGAN is pretty detailed as your code.
I'm trying to port ESRGAN to Tensorflow using Keras. 
I've built the model, and completed first stage of training on PSNR-oriented model.
However, some weird artifacts appears on images as you can see in attached files.

<img width="1213" alt="capture d ecran 2019-02-23 a 17 52 44" src="https://user-images.githubusercontent.com/47924065/53289282-7b031d80-3794-11e9-95d7-e1412f1ad983.png">

<img width="1206" alt="capture d ecran 2019-02-23 a 17 58 07" src="https://user-images.githubusercontent.com/47924065/53289295-9c640980-3794-11e9-83de-85a9c7ee8810.png">

Do you have any idea of the provenance of this artifacts?

I had done a quick training test with only 2 RRDB blocks instead of 23; and surprisingly, there were fewer of these artifacts (but there were a few anyway).
Do you think the more the model is deep, the more it creates artifacts?

Thanks in advance for your reply!

**Comment by oubathAI** [comment]
I found the cause of these weird artifacts; it was because I had some pixels value out of [-1 1] range and when I scaled back to 255 and cast to uint8 I didn't take these values to account.
I'll use tanh activation on the last layer to avoid this effects.
But I had a question; did you have any specific reasons for not putting tanh activation on the last layer?

**Comment by xinntao** [comment]
@oubathAI 
The reason why I do not use tanh at the last layer:
1) I put the values in [0,1]
2) The network can learn the mapping and most of the output pixel values are in [0,1]
3) When turning it into an image, I first clip it to [0,1]. And found that the final results are good enough. 

It is OK that you use tanh function at the last layer if you put the values in [-1, 1].

**Comment by oubathAI** [comment]
Ok, great to know that I don't need to retrain the model from scratch then :) 
Have a nice day!
