### ISSUE TITLE
Images (Multi-spectral) with more than 3 RGB channels

### ISSUE THREAD

**Issue by Jing25** [xinntao/BasicSR#75]
Hi, I don't understand why we need color conversion in SR? If I have images with more than 3 channels, what should I do?

**Comment by xinntao** [comment]
The conversion in BasicSR codes is to convert RGB to gray and so on. 

If your images are more than 3 channels, you can define your own data loader, read it and train the network.

**Comment by Jing25** [comment]
So... why we need to convert RGB to gray? Is it because that converting to gray is fair for metrics comparison, such as PSNR?

**Comment by xinntao** [comment]
In some applications, we only process the Y channel in YCbCr. 
So we need to train the corresponding model in Y channel or gray channel.
