### ISSUE TITLE
Some concerns on usage

### ISSUE THREAD

**Issue by onurctirtir** [xinntao/BasicSR#8]
I don't know if opening an issue for this is appropriate or not but I stuck around at some point:

1) In SFTGAN.json, what is expected for "datasets:dataroot_HR_bg:" ? What 'bg' corresponds for ?
2) If I'm not wrong, I should put HR images under 'img/' at some directory and '.pth' files under 'bicseg/' being in the same directory with 'img/'

Thanks in advance

**Comment by xinntao** [comment]
@onurctirtir 

1. bg is for background category. We train other categories with OST dataset and background category with the DIV2K dataset. 
2. You are right. A brief description https://github.com/xinntao/BasicSR/tree/0.4/codes/data

**Comment by onurctirtir** [comment]
Thanks!
