### ISSUE TITLE
Why the input of VGGFeatureExtractor need to do normalize ? 

### ISSUE THREAD

**Issue by lzw-all-in** [xinntao/BasicSR#99]
I'm curious about that because the input already in range of [-1, 1] or [0, 1] .
Thanks !

**Comment by xinntao** [comment]
The VGG inputs need to consider the mean and std normalization.

**Comment by lzw-all-in** [comment]
@xinntao 
Thanks for ur reply .
But I had another problem : why do the normalization with some fixed value such as [0.485, 0.456, 0.406] in ur code ? what is the intuition behind it ?

**Comment by xinntao** [comment]
This is determined during training the VGG model for image classification. Please refer to the VGG paper.

**Comment by lzw-all-in** [comment]
Thx, my apology to take up your time .
